### ISSUE TITLE
I changed the quest book back to normal but now i dont know how to change back

### ISSUE THREAD

**Issue by Piesda** [Wynntils/Wynntils#1018]
![Ekran görüntüsü_20230111_145956](https://user-images.githubusercontent.com/122451196/211801459-f01be41e-8022-4634-9cbd-effa28093ea9.png)

**Comment by kristofbolyai** [comment]
ESC, Wynntils menu. In the future, use discord, #artemis-support for these kinds of issues

**Comment by Piesda** [comment]
Also tracked quest is stucked at the top right corner even if i click twice to that quest it still shows at top right
