### ISSUE TITLE
not all placeholders have aliases, so they cannot be used in info-boxes

### ISSUE THREAD

**Issue by KamikotoTkach** [Wynntils/Wynntils#1026]
At https://github.com/Wynntils/Artemis/blob/main/common/src/main/java/com/wynntils/functions/CharacterFunctions.java not all placeholders have aliases, so they cannot be used in info-boxes

**Comment by kristofbolyai** [comment]
You can use the actual name to place it in info boxes. Do /function list ingame to see all variabless

**Comment by KamikotoTkach** [comment]
xp per minute is not there, which is what I need
