### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by WarpedVoxel** [Wynntils/Wynntils#1035]
When I join the server with Wynntils installed, Minecraft stops respecting the JVM memory allocation and my system memory fills up.
Minecraft: Minecraft 1.19.3, Fabric 0.14.12, Wynntils 0.0.2-alpha.103, no other mods, 6 GiB memory allocation, Prism Launcher
OS: EndeavourOS Linux (kernel version 6.1.6 zen)
hardware: Ryzen 7 2700X, RTX 3060, 32G memory

**Comment by kristofbolyai** [comment]
What version of Artemis? Edit: sorry I see now

**Comment by kristofbolyai** [comment]
Does it happen on 102?

**Comment by WarpedVoxel** [comment]
It does not appear to, no

**Comment by kristofbolyai** [comment]
I can't get this to happen? I am getting regular memory usage with GCs.

**Comment by andreymlv** [comment]
Same problem:

Arch Linux 6.1.6-zen1-1-zen
Minecraft 1.19.3, Fabric 0.14.12, Wynntils 0.0.2-alpha.103

**Comment by WarpedVoxel** [comment]
I am using build 106 now and the issue is resolved. I don't know what you changed but it seems like it fixed it
