### ISSUE TITLE
ItemRenamedEvent is not calculated properly for crafted items

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#1108]
This is likely caused by crafted item lore containing durability, and if spell cast makes the durability change, then the items won't be "similar", and item rename won't be detected. (I have not confirmed this. But this is a likely theory)

**Comment by kristofbolyai** [comment]
https://github.com/Wynntils/Artemis/issues/1108

**Comment by kristofbolyai** [comment]
Another item transformer related issue: ![image](https://user-images.githubusercontent.com/49001742/216811060-425d8a5d-7332-4f4e-90f7-2ee5d1543a89.jpeg)

**Comment by magicus** [comment]
Fixed by  #1149
