### ISSUE TITLE
Feather client loading Loop

### ISSUE THREAD

**Issue by zayonarts** [Wynntils/Wynntils#1109]
Hi, i have no idea how to figure it out what causes it, i use feather 1.19.3 fabric, and when i activate wynntils-0.0.2-alpha.160-fabric, the minecraft launches but the fabric has it's loading screen that loops over and over again and can't do anything.

Please try making it compatible with feather client as well.

P.S. : This loop is also caused even if i have only the architectury and wynntils mods active, with or without any other mods active beside them, still the same loading loop.

**Comment by kristofbolyai** [comment]
Feather client is closed source and changes the game in many ways. There is no way for us to support something we can't even understand. This means Feather client will be unsupported for the time being.

**Comment by magicus** [comment]
Does the Feather client has a fabric ID so we can add a `conflicts` dependency?

**Comment by zayonarts** [comment]
> Does the Feather client has a fabric ID so we can add a `conflicts` dependency?

I really have no idea how to search that one up.
