### ISSUE TITLE
/Friends list command triggers by joining a new world or closing settings.

### ISSUE THREAD

**Issue by Peter-Marius** [Wynntils/Wynntils#1178]
Whenever I join Wynncraft with Wynntils or join a new world while using the mod, it opens the friends list immediately without me using the command /friends list. This also happens whenever I close the Wynntils settings menu.
I have joined Wynncraft in vanilla minecraft and it doesn't trigger and i even joined with 1.12 Wynntils and it never triggered, only when i used /friends list.

**Comment by magicus** [comment]
I have noted this, too. I think our FriendModel tries to list our friends, and try to hide the reply, but fails.
