### ISSUE TITLE
ClientboundBossEventPacketAccessor is not registered in mixin configs

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#125]
`ClientboundBossEventPacketAccessor`, which is used in `FixPacketBugsFeature` is not registed in `wynntils.mixins.json`. 

@magicus, as you wrote that feature, is there a reason is or was it just a mistake?

**Comment by magicus** [comment]
Just a mistake.

Is there some way we can verify automatically that all classes in the mixin package is properly registered?

(Apart from the obvious: test the feature! ;-))

**Comment by magicus** [comment]
That's probably why it has regressed lately. I was wondering about that...

**Comment by kristofbolyai** [comment]
> Just a mistake.
> 
> 
> 
> Is there some way we can verify automatically that all classes in the mixin package is properly registered?
> 
> 
> 
> (Apart from the obvious: test the feature! ;-))

Perhaps a custom spotless module, not sure if anyone wants to do that though.

**Comment by kristofbolyai** [comment]
> That's probably why it has regressed lately. I was wondering about that...

Let's thank loom for breaking again (that's how I discovered this). 😅

**Comment by kristofbolyai** [comment]
Do you wanna fix this yourself or should I make a quick PR?
