### ISSUE TITLE
Unidentified Revealed Mythics Glow Missing

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#128]
![image](https://user-images.githubusercontent.com/17955785/176984595-d822424f-5c51-44df-b564-f6af8a78792f.png)

Revealed mythics don't glow on the market or in booths. The issue is probably more general - these are just the places where I found it.

**Comment by kristofbolyai** [comment]
I assume this is about revealed items?

**Comment by P0keDev** [comment]
> I assume this is about revealed items?

yes - there's no handling for revealed items at all atm. maybe we should take this opportunity to rewrite our highlight code to use the new `ItemProperty` system - off the top of my head there's boxes, revealed items, ided items, corkian amplifiers, tomes, and charms to support, and the property itself should be pretty trivial
