### ISSUE TITLE
Minimap size

### ISSUE THREAD

**Issue by 64BitUniverse** [Wynntils/Wynntils#1334]
It would be nice to have a scale/size setting for the minimap itself. As it is right now, it feels like the minimap takes up a significant part of my screen. If I want it to be smaller, I can lower the GUI Scale, but then my hotbar becomes unreadable.

**Comment by kristofbolyai** [comment]
Every overlay's size is editable, in the overlay configuration screen.

**Comment by magicus** [comment]
I do agree however that our minimap is unreasonably large at some GUI scales. We should probably look into how it is scaled according to the GUI scale, so the default is not so extreme as it is right now.

**Comment by magicus** [comment]
Let's leave the default as now. There is also hotkeys for zooming the minimap now.
