### ISSUE TITLE
Map is a bit messed up

### ISSUE THREAD

**Issue by billsboard** [Wynntils/Wynntils#1411]
Updating to wynntils 408 causes the in game map to have artifacts appear on it.

![image](https://user-images.githubusercontent.com/31022753/228986523-7afe6f46-7aa1-48be-a10e-6678f470a7e3.png)
![image](https://user-images.githubusercontent.com/31022753/228986580-9ca15ff8-fb0e-4437-bbdc-27c5c704b6c6.png)

This seems to be associated with the loot chest icons (clicking on the glitched texture compasses to loot chests).

**Comment by kristofbolyai** [comment]
Fixed in latest.
