### ISSUE TITLE
mc().player is null

### ISSUE THREAD

**Issue by magicus** [Wynntils/Wynntils#1427]
We have gotten s handful of crashes, where mc().player is null. This should not really be the case if we send out events, since then we should be connected. player is only set to null in Minecraft.clearLevel() and we should not be able to reach that without registering a disconnect, which should stop all events. Nevertheless, we have crashes:

https://athena.wynntils.com/crash/view/05c79db202d349edd63bfd7b6bdc411a
https://athena.wynntils.com/crash/view/bc9e19c3d2ea413fc53b01e346d7d395

**Comment by kristofbolyai** [comment]
This is fixed by #1522
