### ISSUE TITLE
Bomb Bell Ignores All Information But Prefixed Chat Alerts

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1430]
There are three types of bomb information:
1. Champion Bomb Bell
2. general announcement in chat (when in the same world)
3. boss bar status messages

While ⑴ works flawlessly, neither ⑵ nor ⑶ are used to complement the information. Scenario where this matters:  
Players often quickly switch servers when they get the Bomb Bell notification. While they're between servers, another bomb might be thrown (e.g. combat/loot or prof-xp/speed pairs). This means, that only the first one is registered, as types ⑴ and ⑵ cannot be received between worlds. Additionally Bomb Bell has varying delay, so channel ⑶ could be used to improve timer accuracy.

The message shown when you're in the same world as the thrower could be parsed similarly to the Bomb Bell. It just doesn't have this nice prefix and adds some information about the bomb type.

In the boss bar info time is in remaining minutes, with seconds cut off (19:59 shows as 19 min). This creates the under-estimate `min` and over-estimate `min + 1`. With this a new timer with estimate `min + 0.5` can be created, or an existing timer be adjusted with `newTime = clamp(min,  min+1, curTime)`.

With these additional data channels, the feature can benefit all players, rather than just Champions. At that point it's probably justified to create an overlay for the registered bombs.

**Comment by magicus** [comment]
Sounds like great ideas! Feel free to implement. ;-)

I'm skeptical about the overlay. I think the use case is more "oh, i want to do some gathering, are there any worlds with bombs on them?", and then you go check it out. So the command has worked quite well for me. An alternative would rather be to add it to the Wynncraft menu, perhaps with a hotkey to open it. Overlays are typically more useful for stuff you need to see at a moments glance while in game play.

**Comment by Kepler-17c** [comment]
I get what you mean about the overlays, though there are more bomb types than just for professions. And it's good to know how long it's going to continue without the need to input some command (or repeatedly smashing a hotkey for said command).

Here are two compromise ideas:
1. A toggle key could be used to show/hide the overlay.
2. The command remains for showing all bombs, while the overlay only shows the current world's bombs.

An overlay also has the purpose of guiding your attention. Without a bomb overlay it's easy to forget when a bomb was thrown.

**Comment by magicus** [comment]
Sure, I will not object to anyone adding functionality they deem relevant, as long as it can be turned off.
