### ISSUE TITLE
[Feature request] BG Audio from audio file

### ISSUE THREAD

**Issue by MenacingPerson** [Wynntils/Wynntils#1438]
While in wynncraft, play the region's noteblock theme from an audio file and disable the actual wynncraft noteblock music (using /music, not the jukebox sound slider in settings). Would help in removing music lag and I suppose some network traffic.

Also allow for customisation of song per region in the mod, maybe?

**Comment by kristofbolyai** [comment]
This is not the place for feature requests. Use the designated channels in our discord. https://discord.gg/wynntils

**Comment by MenacingPerson** [comment]
Sorry. Not used to this.

https://discord.com/channels/394189072635133952/1026936305013239838/1092460336407400560
