### ISSUE TITLE
/party <player> is recognized as an incorrect argument

### ISSUE THREAD

**Issue by imIrony** [Wynntils/Wynntils#1511]
Using `/party <player>` shows as an incorrect argument although it functions as a shorthand to invite players by username similar to using `/party invite <player>`.

**Comment by magicus** [comment]
You can still execute the command and the server will accept it. There is no nice way to get this (badly designed) syntax into the command completion system. 

If you want to type less, you can do "/pa invite", or use tab for completion. Or try out the party management screen!
