### ISSUE TITLE
Trade Market Tax Subtraction

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1523]
Tax calculation mostly works, I just found this instance where it doesn't:

I entered `10eb-t` at the price and this is the result:

![image](https://user-images.githubusercontent.com/17955785/233464494-3c5dd01b-1b2d-4e4d-92db-ad6930b648a8.png)

**Comment by Kepler-17c** [comment]
I manually entered 609 and got this:

![image](https://user-images.githubusercontent.com/17955785/233466343-db0ae404-dc0c-4eba-a1c3-fab30907c8c8.png)

o.O

**Comment by Kepler-17c** [comment]
Seems the taxed price of 10eb is impossible...

How should this be dealt with?
Leave as is or maybe choose the value below?

**Comment by magicus** [comment]
I think we can let it be.

**Comment by magicus** [comment]
Quirk of maths. Nothing we can do.
