### ISSUE TITLE
Dialogue Background and text not correctly aligned when the text is bold

### ISSUE THREAD

**Issue by Zappic3** [Wynntils/Wynntils#1525]
With normal text, everything looks fine, but this is how it looks if the text is bold:
![grafik](https://user-images.githubusercontent.com/79416867/234610456-1f657230-e405-465c-af1e-05c904c31860.png)
It appears as if the background is shifted to the left, while the text is shifted to the right.
This screenshot was taken using the v0.0.3-aplha.10 version for Fabric 1.19.4.

**Comment by kristofbolyai** [comment]
Thanks for the report. However this is a duplicate of https://github.com/Wynntils/Artemis/issues/283. Feel free to report anything in the future.
