### ISSUE TITLE
WynnCraft's mods

### ISSUE THREAD

**Issue by Javimoa95** [Wynntils/Wynntils#1543]
My mods for wynncraft (wynntils 1.19.4) isn't propperly working, is making my client glitch and the screen its a bit moved upwards so to click anything I need to move my mouse downwards to actually click the button. Also when inventory or any other menu is opened, its also moved upwards. I attach screenshots here. I tried reloading textures, uninstalling and installing back and it isn't working

![image](https://github.com/Wynntils/Artemis/assets/72030264/65f76c27-0661-4d27-8214-f2ee80697208)
![image](https://github.com/Wynntils/Artemis/assets/72030264/00b845c8-eb8d-4828-b0a7-1441f13c4c1e)

**Comment by kristofbolyai** [comment]
Feather client is unsupported, modding feather client is almost impossible without glitches due to the nature of Feature's changes which are much more intrusive than they need to be.

**Comment by MenacingPerson** [comment]
Don't use feather client. Your issue will be fixed.
