### ISSUE TITLE
Crashes when paird with optifabric

### ISSUE THREAD

**Issue by JakeZooook** [Wynntils/Wynntils#1546]
optifabric version 1.13.24
https://www.curseforge.com/minecraft/mc-mods/optifabric/files

optifine version 1.19.4_HD_U_I4

**Comment by kristofbolyai** [comment]
We don't and won't support Optifabric as it is too intrusive (like most mods don't support it).

**Comment by JakeZooook** [comment]
is there a different way to use optifine on fabric?

**Comment by kristofbolyai** [comment]
Why: 
https://github.com/MinecraftForge/blog/blob/fd46b91fb6f889357e4a2402a6e099ef712d54f3/content/personal/matyrobbrt/optifine-alternatives.md

Alternatives:
https://lambdaurora.dev/optifine_alternatives/

**Comment by JakeZooook** [comment]
what all should I get from that list of alternatives to match what optifine does. I am on mc 1.19.4 fabric

**Comment by JakeZooook** [comment]
like entity culling sodium and lithium? those seem to be the only ones up to date

**Comment by re-vc** [comment]
read up about performance enhancing mods for fabric here:
https://gist.github.com/HexedHero/aab340a84db51913cb1106c2d85f4e4f

In short
Fabic API: Needed for other mods.
Sodium: Replaces rendering engine, significantly improves framerate.
Lithium: Optimizes game features for better performance.
Starlight: Replaces Minecraft's outdated light engine for improved performance.
Force Close World Loading: Reduces time spent on "Loading terrain" screen.
Krypton: Optimizes Minecraft's networking stack.
Dynamic FPS: Reduces FPS when tabbed out to free up CPU for other tasks.
Enhanced Block Entities: Optimizes tile entities for better FPS.
FerriteCore: Reduces memory usage, recommended for low memory systems.

mix and match as you like
im running **sodium, lithium, starlight, forcecloseloadingscreen, krypton, dynamic fps and farsight**

**Comment by JakeZooook** [comment]
alright, thanks for all the help
