### ISSUE TITLE
StyledText issues

### ISSUE THREAD

**Issue by MenacingPerson** [Wynntils/Wynntils#1580]
~~1. When holding shift, price in merchant inventory is not shown as quadrupled anymore~~ Fixed in 1581

~~2. Lots of text (ability cooldowns, etc) is now green where it wasn't before~~ Confirmed as feature

~~3. Quest book is not loading quests in alpha 54~~ Fixed in 1581

~~4. Press SHIFT to continue message is now shown in chat instead of artemis~~ Fixed in 1581

~~5. Because of aforementioned bug, the dialogue of entities which should persist disappears after some time~~ Fixed in 1581

6. Sometimes random hostile mob bossbars are colored green (aka peaceful mob) when they aren't. Probably because of 2

Partially closed by #1581

**Comment by kristofbolyai** [comment]
I am not so sure about 6., do you have a concrete before - after showcase?

**Comment by MenacingPerson** [comment]
No, it only happened to me once sadly, and I killed the mob. I'll report again if it happens.
