### ISSUE TITLE
Trade Market Sell All Invalid Amount

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1601]
I was selling T2 & T3 granite ingots and tried using the `Sell All` button to auto-enter the amount.

At first I thought it ignored the tier, but even with a single type and tier, the count didn't work correctly. Wynncraft printed "invalid amount" in chat and removed the selected material from the trade market GUI.

Version v0.0.3-alpha.74

![image](https://github.com/Wynntils/Artemis/assets/17955785/7950ea2c-3235-40b7-956e-473346bc71b1)
![image](https://github.com/Wynntils/Artemis/assets/17955785/81a50f33-b107-4594-b42d-d7744ab767cd)

**Comment by kristofbolyai** [comment]
Fixed by #1609
