### ISSUE TITLE
Prof T3 Dry Info Variable

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1614]
![image](https://github.com/Wynntils/Artemis/assets/17955785/cac00425-93fd-4117-9ac3-b5168e3411ba)

Similarly to being mythic-dry, there can be gather streaks of a couple hundred nodes without getting a single T3 item.

For reference - gather success max is 90% and tiers if successful:
- T1 89%
- T2 10%
- T3 1%

(= one T3 every 111 nodes on average)

**Comment by kristofbolyai** [comment]
Added in #1616
