### ISSUE TITLE
placeholder names apear when pressing tab

### ISSUE THREAD

**Issue by Mcrtin** [Wynntils/Wynntils#1639]
the placeholder names from the player info list appear when pressing tab in the chat
![image](https://github.com/Wynntils/Artemis/assets/66840021/c8e387e1-ab42-4764-b252-bf0bc91c2a47)

**Comment by magicus** [comment]
That is from Vanilla.

Or do you mean that we should add a feature to filter these out? I'm guessing that can be tricky, but it probably possible somehow.

**Comment by sofiedotcafe** [comment]
> That is from Vanilla.
> 
> Or do you mean that we should add a feature to filter these out? I'm guessing that can be tricky, but it probably possible somehow.

idk maybe in the minecraft source code would be something?

**Comment by Mcrtin** [comment]
you could filter the players with a blank tab display name

**Comment by magicus** [comment]
Please do not use the bug system on Github to file suggestions/enhancements. See our Discord for the proper way to do this.
