### ISSUE TITLE
Bank/Inventory/Pouch Search

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1648]
In Legacy the bank and inventory have a button that cycles through all crafting professions and highlights ingredients that can be used for it.

Having a search function with highlight for bank, inventory and pouch would be a great help:
- The search box from the bank could be applied to the inventory and pouch as well. (At least the design - I didn't check the implementation details)
- Additional search parameters to cover are:
  - profession type
  - level range
  - item tier
- Search features should be accessible via
  - either a comprehensive search string syntax
  - or additional buttons and text-fields to enter the different parameters.

**Comment by magicus** [comment]
Do you intend to implement this, or is it a general feature request?

**Comment by Kepler-17c** [comment]
This ticket is for:
- feature parity
- idea(s) how to improve the feature
- idea(s) how to merge with existing features

(so more like a feature request - I currently don't find much time to work on Wynntils or my personal coding projects)

**Comment by Etrenak** [comment]
Hello,
For information, I am currently working on adding this feature and will be opening a merge request in a few days when it will be finished.

**Comment by kristofbolyai** [comment]
Already implemented :)
