### ISSUE TITLE
Map tiles are removed from cache even though we cannot download new

### ISSUE THREAD

**Issue by ScarletCurry** [Wynntils/Wynntils#1674]
China blocked the github cdns but I used vpn to make my wynntils successfully download the cache files. item guide and map both are fine if I turn vpn on, but map would be black if I turn it off
And I cannot use vpn to play game because vpn has lantency issue

in-game: https://photos.app.goo.gl/tFVbcb4fX7qFs6xF7
file: https://photos.app.goo.gl/wZ11iz6CmNus98E57

**logs**
with vpn: https://hst.sh/uwuxobukej
without vpn: https://hst.sh/uquhurisog

**Comment by magicus** [comment]
On the description, it sounds like we are invalidating/removing downloaded map image tiles, even though we cannot download new, fresh. That seems like a stupid thing to do. But I don't know if a fix is easy or not.

**Comment by ScarletCurry** [comment]
🤕will be glad to see the fix then

**Comment by magicus** [comment]
Additional information provided in #1891:

> After the refactor of the [MapService.java](https://github.com/Wynntils/Artemis/blob/main/common/src/main/java/com/wynntils/services/map/MapService.java), the function [loadMaps](https://github.com/Wynntils/Artemis/blob/70c1146942ad4d5242e59f4ccc8b63bc08b4cde2/common/src/main/java/com/wynntils/services/map/MapService.java#L43) will abort the map load work if the client cannot link to some specified links, such as dataStaticAbilities, dataStaticMaps, and dataStaticUrls. this result in a black map occurs when you join the Wynncrafft, even if you have a brand new map cache in the cache folder.

**Comment by kristofbolyai** [comment]
@magicus that comment is not entirely true, but I am working on a fix.

**Comment by kristofbolyai** [comment]
@ScarletCurry @TUsama Can you try with the new versions?

**Comment by kristofbolyai** [comment]
(you have to update your caches once first)

**Comment by ScarletCurry** [comment]
> 

the map can load without vpn now
