### ISSUE TITLE
Test Result of Item Tier / Scroll Letters

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#169]
Success:
- scrolls have the town letter
- powders have their tier

Fail:
- Town pairs like Nesaak and Nemract get same letter
- boat passes don't have letters
- broken keys where the Forgery note is missing don't have letters
- old dungeon keys don't have letters
- emerald pouches don't have their tier

**Comment by P0keDev** [comment]
> Town pairs like Nesaak and Nemract get same letter

this is the same behavior as legacy - i'm not sure how we could convey these differences easily

> boat passes don't have letters

not implemented yet

> old dungeon keys don't have letters

is this really a valuable functionality?

> emerald pouches don't have their tier

not implemented

**Comment by Kepler-17c** [comment]
> this is the same behavior as legacy - i'm not sure how we could convey these differences easily

Probably needs specific exceptions - could use syllables (e.g. NA = Nesaak / NR = Nemract / RN = Ragni / RL = Relos / CK = Corkus / CF = Cinfras / ...)

> is this really a valuable functionality?

Not really, but it would be cool to have them treated the same way as modern keys.

> not implemented

I guessed so, but wanted to point it out anyway, so there's a note for planning and future updates.

**Comment by ryanzhoudev** [comment]
> >Town pairs like Nesaak and Nemract get same letter
> this is the same behavior as legacy - i'm not sure how we could convey these differences easily

Since this bit is being rewritten anyway, the town names could get a 2 or 3 letter abbreviation
I felt like the 2 letters were really useful for the dungeon keys, and this could probably benefit the same way

oh kepler was already typing

**Comment by Kepler-17c** [comment]
The syllable thing doesn't allow things like using the first two words (e.g. Lost Sactuary -> LS), so it probably needs a hard-coded map of town name to abbreviation (should be fine though, as they barely change)

**Comment by ryanzhoudev** [comment]
Is hard-coded necessary? I feel like the first three letters of each town name works quite well for nearly every town off the top of my head

RAGni
DETlas
CINfras
AHMsord
LUTho
ALMuj
SELchar
OLUx
GELibord

The only two I didn't really like were CORkus and TROms, but honestly even they are okay

**Comment by Kepler-17c** [comment]
I fear that might be too bulky 🤔 
How about first 2?

**Comment by ryanzhoudev** [comment]
Well first 2 would not solve the problem in the first place - NEmract and NEsaak

**Comment by Kepler-17c** [comment]
Ah, true :/

**Comment by IngeniousCoder** [comment]
Seems like the rendering is done based on the first letter of the item, which shouldn't be the case, and if it is, consider adding checks;

![image](https://user-images.githubusercontent.com/29097583/179932858-9a6cf176-7450-446a-abff-67489dd345c2.png)

Rendering on Auction Page is wrong.

![image](https://user-images.githubusercontent.com/29097583/179932942-591218e9-e094-4a09-8cd8-1b82b926977b.png)

And the inner view further confirms my suspicion the rendering is done based on the first character of the item
