### ISSUE TITLE
Bring back Wynntils Prof-Badges!

### ISSUE THREAD

**Issue by Kroko-fant** [Wynntils/Wynntils#1709]
Prof Badges had been one of the 1.12 features a lot of proffers appreciate. There is a lot of competition around "Top 9" for exactly that reason.

In 1.12. each of the 12 gatherings has a badge plus one extra badge for total all. (so a total of 13 badges)
1. \- 3. Gold Badge
4. \- 6. Silver Badge
7. \- 9. Bronze Badge

A player can have one or more badges as shown in the screenshots below. The badges are displayed above the head of players. I tried to get a screen with a donator and a prof badge but they were competible ofc.

![grafik](https://github.com/Wynntils/Artemis/assets/25010075/3a8c2d1d-4ca9-4211-a31a-12a319df4981)
![grafik](https://github.com/Wynntils/Artemis/assets/25010075/d93f8d7d-e1f3-425a-a16c-c953db43a2f9)
![grafik](https://github.com/Wynntils/Artemis/assets/25010075/e9708fb3-56a8-4783-bceb-e71de7de0a4f)

**Comment by orengrr** [comment]
yes pls
