### ISSUE TITLE
Wynnic/Gavellian Tooltip

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1715]
Legacy has options to replace Wynnic/Gavellian text or have the translation as tooltip when hovered in chat.

**Comment by ShadowCat117** [comment]
![2023-07-18_20 37 03](https://github.com/Wynntils/Artemis/assets/8337467/fd5dd9b4-f83c-4808-801d-5934e61d232c)
![2023-07-18_20 36 36](https://github.com/Wynntils/Artemis/assets/8337467/7911b62d-8d75-4562-bc54-075978beeb4c)
![2023-07-18_20 39 56](https://github.com/Wynntils/Artemis/assets/8337467/75c14474-64b3-4051-aaf0-c0c435ad1630)

Got some basics working for this :)

**Comment by ShadowCat117** [comment]
No tooltips yet but chat and NPC dialogue is added in https://github.com/Wynntils/Artemis/pull/1901

**Comment by magicus** [comment]
Actually, adding tooltip hovers to chat is not very difficult, given the nice work you did on the transcription PR. You need to split the StyledText into pieces, with a split each time the alphabet is changed. Then you just combine them back together, and add a onHover attribute to the gavellian/wynnic parts. (I am not sure we have full support for onHover for StyledText so you might need to convert it to a Component first to be able to do that.

You can probably find some inspiration in the "item in chat" feature, which does something similar for our encoded items.

**Comment by ShadowCat117** [comment]
Oh yeah difficulty wasn't the issue, it's more of unsure how to handle NPC dialogue as that gets redirected to the overlay and it's not really intuitive to hover that

**Comment by magicus** [comment]
We can use the same workaround as for multi-option npc messages, and also send a copy to the chat of those messages. It's by no means perfect, but it does make it possible to add hovering, if you want to have the ability to have a sneak look, but chose if you want to see it.

**Comment by ShadowCat117** [comment]
Ok I'll look into that after finishing my waypoint manager redesign ;)

**Comment by magicus** [comment]
You might want to look at what is coming soon in terms of the new mapdata system: https://github.com/Wynntils/Artemis/pull/1814

Basically waypoints ("map features" in the terminology of the new system) will have a bunch of attributes, which it can either override on a per map feature basis, or inherit from it's category (or the category's parent category, etc).

**Comment by ShadowCat117** [comment]
Yeah I've had a peek, mostly just changing how it looks for the moment and I might not even pr it until you've finished with that so I don't have to revisit it again afterwards. Only new thing I've got at the moment is a search bar but I also want to add the filtering by icon, but since the new system will have custom icons I'm waiting on that.

Just want to redo my early contributions to make them better and I have an interesting idea for the seaskipper that hopefully I can pull off ;)

**Comment by ShadowCat117** [comment]
Done https://github.com/Wynntils/Artemis/pull/1961
