### ISSUE TITLE
Gather Cooldowns When Switching Worlds

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1716]
Legacy has a timer overlay that shows how long you have to wait before opening chests or being able to gather.

With chests this is a bit more complicated as different tiers have different cooldowns (which I don't know - please comment below if you do).

Gathering is always 60 seconds after world join without prof speed and 30 seconds with prof speed.

**Comment by magicus** [comment]
Tool chest cooldown is a moot point with 2.0.3 -- all chests have individual cooldowns, which are shown in-world.

I'll repurpose this to track the feature gap with Legacy for gather cooldowns.
