### ISSUE TITLE
Dry Streak Message and Info Variables

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1717]
Dry streak counters are great, but would be even better if you were told at what number you broke the streak. Currently you have to watch the numbers go up and either record with OBS or keep the last value in your head.

- add chat message for dry streak breaking
- add function for last dry streak
- add function for highest dry streak

**Comment by magicus** [comment]
Please use the feedback site for general enhancement/improvement ideas.

**Comment by Kepler-17c** [comment]
At least the chat messages are for feature parity - why should that be posted to the feedback site?

**Comment by kristofbolyai** [comment]
> At least the chat messages are for feature parity - why should that be posted to the feedback site?

It's already PRd, don't worry about it

**Comment by magicus** [comment]
In  #1787 (for future reference)

**Comment by magicus** [comment]
@Kepler-17c If you file bugs with missing functionality from Legacy, please keep the bug to just the missing functionality.
