### ISSUE TITLE
[2.0.3] content book parsing is too slow

### ISSUE THREAD

**Issue by magicus** [Wynntils/Wynntils#1729]
Consider removing the trailing filter reset to speed up things.

Additionally, we should save the last read content items in a Storage (per character), so we can present the Quest Book immediately, and then reload in the background.

**Comment by kristofbolyai** [comment]
The cause is rather obvious, when taken a closer look. We have 5 use cases of content book parsing.

Quest book screen runs 2 separate full queries for mini and normal quests.
Discovery screen runs 3 separate full queries for it's discovery types.

We need to look at reducing this.

**Comment by kristofbolyai** [comment]
Not worth to keep this issue, this most likely stays until we change the content book to be a wrapped screen.
