### ISSUE TITLE
Error with one of the first quests where you have to open your quest book

### ISSUE THREAD

**Issue by charlesoestergaard** [Wynntils/Wynntils#1750]
![image](https://github.com/Wynntils/Artemis/assets/59709554/7f7c3e74-b4fa-42c8-800c-799556831ae8)

**Comment by kristofbolyai** [comment]
Discord announcements: 
> Update: Artemis 0.0.3-alpha.133 fixes the content book not working with the tutorial.

Please use discord next time, we will create issues, if needed.

**Comment by charlesoestergaard** [comment]
Sorry i dident know that. Do you want me to delete this issue.

**Comment by kristofbolyai** [comment]
I closed it, it's fine
