### ISSUE TITLE
archivesBaseName is depracated, will be removed in Gradle 9

### ISSUE THREAD

**Issue by magicus** [Wynntils/Wynntils#1758]
We must figure out a replacement. I tried following the docs but my gradle/groovy knowledge was too thin for me to understand what I should do, since my trivial attempts failed.

**Comment by xCykrix** [comment]
@magicus Closed by the above merged, just FYI. Didn't link correctly it seems haha. Happy to help though, random knowledge I just happened to already have a problem with recently.
