### ISSUE TITLE
Custom Loading Screen Stays When Joining Another's Housing

### ISSUE THREAD

**Issue by Kepler-17c** [Wynntils/Wynntils#1802]
I can reliably reproduce it myself and I've seen others have the same issue when I invite them to my housing:

When you click on a housing invitation, you're teleported and the custom loading screen is activated. However the screen stays active until you press `Esc` to manually close it. It doesn't close automatically as it should.

**Comment by geekazodium** [comment]
... yall I think I found the cause for the bug

**Comment by geekazodium** [comment]
when you join housing the house name is set in the place where the world name SHOULD be so it doesn't match with the matcher that detects if the world has been changed.

**Comment by geekazodium** [comment]
*working on a fix

**Comment by geekazodium** [comment]
fix is now complete.
