### ISSUE TITLE
Player ghost transparency feature makes every player transparent, including NPCs, same-server players and own player

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#19]

**Comment by Incompleteusern** [comment]
It works for me on fabric. Note that the code governing this is
```java
    private static final Pattern PLAYER_GHOST_REGEX = Pattern.compile("_\\d+");

    public static boolean isPlayerGhost(Player player) {
        Team team = player.getTeam();

        if (team == null) return false;

        return PLAYER_GHOST_REGEX.matcher(team.getName()).find();
    }
```

Perhaps a patch changes it on forge.

**Comment by kristofbolyai** [comment]
On fabric, it does not seem to work at all, but it might be Wynncraft related. 
![2022-02-24_19 41 01](https://user-images.githubusercontent.com/49001742/155587083-217dd035-4504-4cdc-a321-6b2f5c8ad58f.png)
![2022-02-24_19 40 56](https://user-images.githubusercontent.com/49001742/155587402-194ef99a-2f42-4f47-a0ef-fab5a5c8d992.png)


EDIT: Actually am I blind and is it working? Let me test with lower transparency.

**Comment by kristofbolyai** [comment]
Nevermind, it does actually work on Fabric. Let me get some screenshots of Forge.

**Comment by kristofbolyai** [comment]
Forge: 
![2022-02-24_19 50 42](https://user-images.githubusercontent.com/49001742/155588446-b4929f95-69a7-4cdc-af3c-2645d25bd89e.png)
![2022-02-24_19 50 47](https://user-images.githubusercontent.com/49001742/155588467-e8a72f61-f0fa-44da-b9a4-9eb48e59fdd3.png)
![2022-02-24_19 50 55](https://user-images.githubusercontent.com/49001742/155588498-23cfa3d9-2ffd-47a1-bfa6-1a4a33705e76.png)
