### ISSUE TITLE
If an NPC has >9 options, there's no way to select 10+ option dialogue

### ISSUE THREAD

**Issue by Chew** [Wynntils/Wynntils#1964]
I was having a conversation with "Silverbull Beacon Expert" and realized I had no way of clicking 10-13. I had to type `/class` and come back.

## Wynntils Version

`0.0.3-alpha.286` (Fabric version)

**Comment by kristofbolyai** [comment]
Use /dialogue <index - 1>. I think we do not send the message out correctly, otherwise people wouldn't report this so much, @magicus.

**Comment by Chew** [comment]
I forgot the screenshot :skull:. But I agree having a "Run /dialogue <x - y>" under it would be helpful too. I don't know how many NPCs even have more than 9 options. Thank you for the quick response :)

**Comment by kristofbolyai** [comment]
To confirm, the dialogue is not sent in chat right? When it has too many options, it should be. @Chew

**Comment by Chew** [comment]
I don't see anything in chat, no. I've seen it there before for reference but not when there's 9+ options.

**Comment by magicus** [comment]
It should have been sent in chat as well. But possibly we only do that if the dialogue is protected. We should do it always if the number of options is > 9.

**Comment by kristofbolyai** [comment]
Fixed in #2358
