### ISSUE TITLE
NPC dialoge does not appear in chat when NPC dialoge overlay is disabled.

### ISSUE THREAD

**Issue by ItsDaCreeper** [Wynntils/Wynntils#2011]
Title says it all. Instead of npc dialoge in chat being hidden only when the overlay is turned on, it is hidden all the time instead, which it shouldn't.

Using v0.0.3-alpha.315

**Comment by derivated** [comment]
I would like to add to this by saying that there appears to be 2 config options to turn off NPC Dialogue, which both cause the issue above.
![image](https://github.com/Wynntils/Artemis/assets/63129353/2e619274-d6cd-4dcf-94b1-885efd76e73a)

**Comment by kristofbolyai** [comment]
Read faq. Disable chat tabs

**Comment by kristofbolyai** [comment]
Fixed in #2358
