### ISSUE TITLE
NPC dialogue flashes/gets added excessive times

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#2016]
Reproduce by taking a seaskipper ride, then talk to any NPC (I talked to llevigar seaskipper this case)

![image](https://github.com/Wynntils/Artemis/assets/49001742/115bda49-0790-4a9c-a286-663bd853fbb9)

**Comment by Nidoskull** [comment]
Can confirm, this is from the Hearthfire Keeper in Detlas after seaskippin' to Selchar.
![image](https://github.com/Wynntils/Artemis/assets/109077284/0baf5f8f-3f42-4822-ac32-91ac29d57f39)

**Comment by kristofbolyai** [comment]
Should be fixed now.
