### ISSUE TITLE
Create regex test system

### ISSUE THREAD

**Issue by magicus** [Wynntils/Wynntils#2049]
See e.g. #2046. 

We need to have a simple framework for junit to write tests for our regexs, so we stop need to relying on external web services, and can include the test regexp strings in the code.

**Comment by geekazodium** [comment]
working on it
also ummmm

**Comment by geekazodium** [comment]
while testing if the unit tests work I found an issue with one of the regexs we were using...

**Comment by kristofbolyai** [comment]
Can you consult with us on how you plan to create this system? It is a major system so there is a chance we will not accept it..

**Comment by geekazodium** [comment]
I'll open a pull request with my implementation

**Comment by geekazodium** [comment]
#2051
