### ISSUE TITLE
Artemis seems to be incompatible with Exordium

### ISSUE THREAD

**Issue by Winqov** [Wynntils/Wynntils#2050]
Description:
Game crash when loading Artemis alongside Exordium. Removing one or the other fixes the issue.

Exordium mod: [https://modrinth.com/mod/exordium](url)

Fabric: 0.14.22
Fabric API: 0.87.0
Artemis: 0.0.3-alpha.346
Exordium: 1.1.2

**Comment by kristofbolyai** [comment]
We can't resolve this.

**Comment by magicus** [comment]
@kristofbolyai If we are incompatible with Exordium, maybe we should state so in our fabric.json file? I agree that Exordium seem to make heavyhanded changes.

@winqogjy Exordium says this on their modrinth page: "I haven't tested it with every mod out there. If you find a mod that doesn't work with this mod, you can report it on Github(but there is no guarantee that it will be fixed)." Their issue reporting page is https://github.com/tr7zw/Exordium/issues

**Comment by kristofbolyai** [comment]
> @kristofbolyai If we are incompatible with Exordium, maybe we should state so in our fabric.json file? I agree that Exordium seem to make heavyhanded changes.
> 
> 
> 
> @winqogjy Exordium says this on their modrinth page: "I haven't tested it with every mod out there. If you find a mod that doesn't work with this mod, you can report it on Github(but there is no guarantee that it will be fixed)." Their issue reporting page is https://github.com/tr7zw/Exordium/issues
> 
> 

Is not it already there? I think @donkeyblaster updated the list a few days ago.

**Comment by magicus** [comment]
I see, found it. Nevermind then.
