### ISSUE TITLE
Mana Bar and Powder Special Bar is not working properly when Curse is at 100%

### ISSUE THREAD

**Issue by Tetro48** [Wynntils/Wynntils#2100]
Steps to replicate:
1. Get and use a weapon with Curse powder special
2. Attack mobs (or housing combat dummy) with main attack until Curse reaches 100%
3. Cast any spell 

Expected behaviour:
- Mana Bar will reflect on mana consumed.
- Powder Special Bar can show 100%

Actual behaviour:
![image](https://github.com/Wynntils/Artemis/assets/76738929/a9569aaf-b87e-4e28-9e15-f2c9e5bb0055)

**Comment by ryanzhoudev** [comment]
Can reproduce, special bar should also reset/disappear when selecting a new hotbar slot
