### ISSUE TITLE
Map and guild map icons are misaligned and/or improperly sized

### ISSUE THREAD

**Issue by ryanzhoudev** [Wynntils/Wynntils#2102]
Guild map:
![image](https://github.com/Wynntils/Artemis/assets/57310593/5c920ef1-09f5-41b7-8bbc-6abe8be53493)

Normal map:
![image](https://github.com/Wynntils/Artemis/assets/57310593/07385297-f5e9-43fc-a519-d94d1391640e)

**Comment by kristofbolyai** [comment]
Probably a scale issue.
