### ISSUE TITLE
Just Lagging Then Completely Freezing and Crashing

### ISSUE THREAD

**Issue by TrissyTiger** [Wynntils/Wynntils#2115]
idk what is causing it and im not tech person but wynntils artemis keeps starting to lag real hard the freeze then proceed to crash religiously ever hour or so. please look into this.

**Comment by ryanzhoudev** [comment]
Provide logs, including information about your modloader, Wynntils version, mod list, and what you were doing at the time please

**Comment by kristofbolyai** [comment]
Closing, inactive.
