### ISSUE TITLE
Emerald Count icons being wrong in other containers

### ISSUE THREAD

**Issue by cKnei** [Wynntils/Wynntils#2121]
In some inventory screens, the emerald count is correct but shows the wrong form of currency. shows proper currency while holding shift.

With Shift Loot run end chest
![image](https://github.com/Wynntils/Artemis/assets/76569087/22b88cc2-5dad-42cd-b9f9-6c0420a2a26a)
Without Shift
Loot run end chest
![image](https://github.com/Wynntils/Artemis/assets/76569087/e2320ff4-4cdd-4008-bbfb-305761837bf8)
Item Identifier (this one should show 46le and 5eb)
![image](https://github.com/Wynntils/Artemis/assets/76569087/25f47d79-07f8-493e-bedf-75c946491b2f)

**Comment by ryanzhoudev** [comment]
This only occurs when the Show Zero Values in Emerald Count setting is Disabled.
