### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LordSeabass** [Wynntils/Wynntils#2127]
Just crashes everytime I start it after the 1st time.  Happens even with fabric and others, but I mainly use forge.

Verison: wynntils-0.0.3-alpha.389-forge+MC-1.19.4

Log: [Here](https://pastebin.com/akENc5Gh)

Crash Report: [Here](https://pastebin.com/uSGHEyZy)

**Comment by kristofbolyai** [comment]
delete your server-resource-pack folder
