### ISSUE TITLE
Scoreboard field in lootruns (timer, challenges, etc...) does not update

### ISSUE THREAD

**Issue by Molioron** [Wynntils/Wynntils#2196]
**Version**
0.0.4-beta.35 and 0.0.3-alpha.380

**Brief Description**
The right side scoreboard UI does not update while there is a mission active (and possibly because the guild's weekly objective also appears)

Moreover, the latest beacon does not disappear upon completion.

**Steps to Reproduce**
1) have a guild weekly objective
2) start a mission in a lootrun

**Expected Behaviour**
the side scoreboard updates as usual (timer, number of challenges, etc...)

**Actual Behaviour**
the side scoreboard will not update until the objective of the mission is complete.
the latest beacon does not disappear upon completion.

**Comment by kristofbolyai** [comment]
Seems to work for me? Any specifics? I have an idea what causes this issue, but if I can't get it to happen, I can't really think of a fix.


![image](https://github.com/Wynntils/Artemis/assets/49001742/32d6912b-96d5-4ca6-a3df-5494604032ea)

**Comment by Molioron** [comment]
Well, for me at least, both daily and guild objectives did not appear in the scoreboard but rather as separate UI components.
(I also had the High Roller mission active and the guild objective completed, but I doubt that they are relevant to this bug).

**Comment by kristofbolyai** [comment]
Yes, it is only showing the objectives on sb for me so I can see how it looks like. Okay, I will check what I can do..

**Comment by xProSen** [comment]
any fixes yet?

**Comment by kristofbolyai** [comment]
Yes, just started working on a fix.

**Comment by xProSen** [comment]
any eta?

**Comment by magicus** [comment]
@xProSen Please be patient. Remember that this is a project fully driven by volunteers. Asking for ETA on such projects are considered bad tone.
