### ISSUE TITLE
Fast Travel Map Enhancement

### ISSUE THREAD

**Issue by Eutropios** [Wynntils/Wynntils#2225]
Hi there,

It'd be neat if you could include all forms of fast travel on the map (ex: Detlas-Alekin Village Carriage, Nemract-Tempo Town Obelisks). It'd also be nice to have each Fast Travel point labelled with its respective destination, or somehow indicate that "fast travel point `x` corresponds with fast travel point `y`".

**Comment by kristofbolyai** [comment]
Enhancements are generally suggested through discord. We will work on this issue separately, it is not directly a problem with the mod.
