### ISSUE TITLE
Quest Waypoint Icon not appearing

### ISSUE THREAD

**Issue by Eutropios** [Wynntils/Wynntils#2239]
Icons and distance for waypoints do not appear while in the Mesas. Icons *do* appear however when in Llevigar.
Running `Wynntills 0.0.4-beta.64` with default-ish* settings on `Fabric Loader 0.14.24`.
The problem still occurs when turning off Sodium, Indium, and Lithium.
*Only modified a few keybinds.

![image](https://github.com/Wynntils/Artemis/assets/64815328/271b06c4-6e8b-4ea8-a7c2-e90ededff237)

**Comment by ShadowCat117** [comment]
I believe waypoint icons and distance do not render when they are further than 5000 blocks away, in this case yours is 5100 so it is not rendering

**Comment by Eutropios** [comment]
> I believe waypoint icons and distance do not render when they are further than 5000 blocks away, in this case yours is 5100 so it is not rendering

Is this due to client-side settings, Wynntills, or just Minecraft in general?

**Comment by ShadowCat117** [comment]
Wynntils, if you look for World Waypoint Distance in the config, you can edit the number
