### ISSUE TITLE
ChatManager wrong chat type

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#224]
@magicus 
![image](https://user-images.githubusercontent.com/49001742/182939598-31382771-d4dd-47b7-9c5a-97f23b797301.png)
`[21:45:06] [Render thread/INFO] (Minecraft) [CHAT] BACKGROUND-PARTY: §r§8[§r§7VIP+§r§8] §r§7FancyFedora§r§8 has just logged in!`

This breaks `InfoMessageFilterFeature` as expected.

**Comment by kristofbolyai** [comment]
![image](https://user-images.githubusercontent.com/49001742/182940626-c9692fef-8764-4b32-ad78-beb2c65f5bef.png)

Shift clicking soul points, assigned different types, not sure if that is what you want.

**Comment by HighCrit** [comment]
![image](https://user-images.githubusercontent.com/35771251/183042511-6b791fed-f6ff-430e-ac0b-eb596a740c55.png)
What is the distinction between the messagetypes normal and system? As I expected bomb bells to be classified as system, but they're not.

**Comment by magicus** [comment]
Thanks for the reports, I'll look into them!

**Comment by magicus** [comment]
@HighCrit THe difference is if Wynncraft tags the chat packet as `CHAT` or `SYSTEM`. I don't know the reason for their choice, or if it has any practical difference. (They look the same to the user.) I assume this is a vanilla distinction that does not really apply to Wynncraft. But the difference is yet another clue for us to correctly differentiate between certain types of messages.

**Comment by magicus** [comment]
@kristofbolyai With different types, you mean SYSTEM/NORMAL? As I said to HighCrit above, that is basically just reporting what Wynncraft choose.

**Comment by kristofbolyai** [comment]
> @kristofbolyai With different types, you mean SYSTEM/NORMAL? As I said to HighCrit above, that is basically just reporting what Wynncraft choose.

Yeah, it is fine them, except the issue description.

**Comment by kristofbolyai** [comment]
![image](https://user-images.githubusercontent.com/49001742/183655175-2a63c78d-62ce-4bb7-9545-3aa04d0fcf69.png)
 I think this issue is related. Shown on joining game.

**Comment by kristofbolyai** [comment]
(Only some text is filtered)

**Comment by magicus** [comment]
What do you mean? The general advertising done by Wynncraft is not filtered. This is due to two reasons:
1) It's a lot of different messages, and hence a lot of additional filters, and
2) I felt it was not really fair -- Wynncraft need their chance to do some advertising. (I might reconsider this point if the user has a paid rank, then they have contributed and know about the situation.)

**Comment by kristofbolyai** [comment]
Ah, I see. Okay then.

**Comment by Incompleteusern** [comment]
> @HighCrit THe difference is if Wynncraft tags the chat packet as `CHAT` or `SYSTEM`. I don't know the reason for their choice, or if it has any practical difference. (They look the same to the user.) I assume this is a vanilla distinction that does not really apply to Wynncraft. But the difference is yet another clue for us to correctly differentiate between certain types of messages.

Late, but vanilla client allosw user to filter SYSTEM or something.

**Comment by Incompleteusern** [comment]
This also should be fixed by #296, so closing until if it reappears.
