### ISSUE TITLE
Hero's range visualizer

### ISSUE THREAD

**Issue by ariszz** [Wynntils/Wynntils#2296]
The Hero's major ID range visualizer wasn't working for me in beta.102, so I switched back to beta.50, which resolved the issue. Found out that it stops working in beta.79 and so on.

Fabric: 0.15.3
Artemis: v0.0.4-beta.102

**Comment by magicus** [comment]
beta.79 includes a single PR, https://github.com/Wynntils/Artemis/pull/2271. Are you saying the visualizer worked  up until 78, but stopped working in 79?

There is nothing obvious in #2271 that would break the hero's range visualizer, but perhaps gear identification was affected by the changes in it.

**Comment by kristofbolyai** [comment]
A few patches earlier we did change the feature to use the major id names, not the wynn internal names. I've checked it and nothing looks visually wrong, and Guardian also works. So I am not sure what happened..

**Comment by ariszz** [comment]
Hero's major ID is "Saviour’s Sacrifice", but in the code, it is "Saviour's Sacrifice" with an apostrophe instead of a right single quotation mark. Could this be the issue?
![image](https://github.com/Wynntils/Artemis/assets/97434144/30306cb0-213e-4824-8262-0e3be2c1948e)

**Comment by kristofbolyai** [comment]
It probably is. I'll fix it up later.

**Comment by ryanzhoudev** [comment]
Fixed in #2301
