### ISSUE TITLE
InfoMessageFilterFeature regex incorrect

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#230]
I think the `LEVEL_UP_1` regex is incorrect. I played today, and the message looked like `user is now combat level 10`, not matching the regex, `^§6.* is now level .* in §.*$`. Is that regex only working for professions?

**Comment by kristofbolyai** [comment]
@magicus

**Comment by magicus** [comment]
Yeah, I did not think of it, and never saw someone level up during my testing. I modified `LEVEL_UP_2` to handle both profession and combat level updates.

You did not save the entire chat message with formatting? :(

**Comment by kristofbolyai** [comment]
> Yeah, I did not think of it, and never saw someone level up during my testing. I modified `LEVEL_UP_2` to handle both profession and combat level updates.
> 
> 
> 
> You did not save the entire chat message with formatting? :(

Yeah, if I did I would have fixed it :c.

**Comment by magicus** [comment]
I think this is fixed now. But these messages are few and far between. Please re-open if you see it again.
