### ISSUE TITLE
Translation bug when "press shift" flashes

### ISSUE THREAD

**Issue by edshPC** [Wynntils/Wynntils#2309]
When you do not continue the dialogue with an NPC for some time, the inscription “press SHIFT to continue” begins to flash in red.
Therefore, when the translation utility is turned on, it begins to try to translate the dialogue again every time this sign blinks. The text does not have time to be translated and appear before it disappears again. it also creates a lot of spam and makes the translation basically useless.
It would be good if the translator ignored the blinking sign and did not try to translate every blink

https://github.com/Wynntils/Artemis/assets/116029298/bfc3684a-3294-4b44-bfaa-5810b5ea9cd9

Artemis: v0.0.4-beta.109

**Comment by kristofbolyai** [comment]
This is now tracked in #2356
