### ISSUE TITLE
[Question] The Urls.json cannot be replace by using Resouces pack

### ISSUE THREAD

**Issue by TUsama** [Wynntils/Wynntils#2341]
kinda a dumb question but the dataStatic things in Urls.json is pretty hard to get due to the Internet difference. I try to use Resouces pack to redirect the links to some mirror but it just doesn't work.
I found that the Urls.json is read by the method getResourceAsStream(), so I wonder if it's possible to read that file by through the ResoucesLocation? That will make it available to be overwritten by the Resouces pack.

**Comment by kristofbolyai** [comment]
`getResourceAsStream` is a Java native method for reading a jar's packed file. It has nothing to do with Minecraft and resource packs. We know that China blocks Github, we are planning to migrate to AWS for this reason. Afaik, there is a Chinese fork for Artemis, that patches the urls file, however, I can't link it.

As for your question, no, you can't change the urls.json file from a resource pack, and from a suggestion standpoint, you should not do it.

I'll consult our team on when we would be able to migrate to AWS, until that point, I can't offer a solution. I am going to open a separate pinned issue for tracking this, though.
