### ISSUE TITLE
[Question] About the resource download issue of Chinese Players

### ISSUE THREAD

**Issue by TUsama** [Wynntils/Wynntils#2349]
I heard there might be a plan this week to tweak things by tossing in some environment variables into urls.json. This seems cool as it could mean no need for a separate build just for Chinese players, but still keeping the Static-storage. Is that really in the works?

I made a Minecraft Fabric mod for version 1.20.2 recently. Used mixin to swap out the JSONs in Wynntils when the JSONs are transformed to string(see [this](https://github.com/TUsama/Wynntils-Url-Redirector/blob/master/src/main/java/com/clefal/mixin/UrlManagerMixin.java)) with solid GitHub mirror links within China. The mod's picking up steam in the Chinese community. But, I'm curious if this mixin trick might accidentally mess with Wynntils. So far, my tests didn't show any issues, but I'd love to hear from your devs.

**Comment by kristofbolyai** [comment]
> I heard there might be a plan this week to tweak things by tossing in some environment variables into urls.json. This seems cool as it could mean no need for a separate build just for Chinese players, but still keeping the Static-storage. Is that really in the works?

Hi! Yes, I am the developer that started this plan. We plan to work on this as soon as possible. Please check out https://github.com/Wynntils/Artemis/issues/2350 for further info on the matter.

> I made a Minecraft Fabric mod for version 1.20.2 recently. Used mixin to swap out the JSONs in Wynntils when the JSONs are transformed to string(see [this](https://github.com/TUsama/Wynntils-Url-Redirector/blob/master/src/main/java/com/clefal/mixin/UrlManagerMixin.java)) with solid GitHub mirror links within China. The mod's picking up steam in the Chinese community. But, I'm curious if this mixin trick might accidentally mess with Wynntils. So far, my tests didn't show any issues, but I'd love to hear from your devs.

No, I don't think the mod has any way to break Artemis, **currently**. However, any further patch to Artemis could create a breaking conflict.

With the proposal implemented, the only thing you need to maintain is a repository/CDN of our Static-Storage, changing the links in `urls.json` (and `maps.json`).

I will now close this issue, and pin #2350 to track it.
