### ISSUE TITLE
ObjectiveOverlay fails to realize completion of objective

### ISSUE THREAD

**Issue by Incompleteusern** [Wynntils/Wynntils#235]
![image](https://user-images.githubusercontent.com/58920010/183266069-f1bebbdd-028e-402f-a402-990ca3c51d51.png)

Likely a parsing error.

**Comment by kristofbolyai** [comment]
Parsing error most likely, happens quite frequently. Usually the problem is in scoreboard reconstruction.

**Comment by magicus** [comment]
I also noticed a several seconds long lag before ObjectiveOverlay updated after switching classes using `/class`. Most of the time it worked fine, and snappy, except when it didn't...

**Comment by kristofbolyai** [comment]
When I fix the parsing error, this all should be resolved. Also, I think some objectives do not get cleared when they reach x/x completion, so we need to handle that (for the objective manager, scoreboard could stay as wynn does it).
