### ISSUE TITLE
Disabling Game Notifications overlay hides all notifications (unless it's parent feature is also disabled)

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#2359]

**Comment by magicus** [comment]
A symptom of the problem with having Overlays as part of a Feature, rather than a first-class citizen. :( I started fixing that but never finished. In the end, I ran into one or two Overlays that did not have a simple 1-to-1 relationship with a Feature, and could not decide how to handle those.

**Comment by kristofbolyai** [comment]
Yes, but at least, it's a relatively simple fix, although a systematic fix is obviously better.
