### ISSUE TITLE
Set items in completed sets aren't highlighted

### ISSUE THREAD

**Issue by HighCrit** [Wynntils/Wynntils#247]
Artemis
![image](https://user-images.githubusercontent.com/35771251/183304870-7910e733-7e9c-40a9-86e8-f7dd490de8d2.png)
Vanilla
![image](https://user-images.githubusercontent.com/35771251/183304951-435cb056-411f-43aa-bc16-3126a353dd97.png)
For some reason the fact that it is a Set item is removed

**Comment by magicus** [comment]
This gives me some déjà vu vibes. I think we had a similar problem in Legacy...
