### ISSUE TITLE
[Function request] Some features that may provide a better experience

### ISSUE THREAD

**Issue by Yurium7** [Wynntils/Wynntils#2504]
Add a 60 second countdown display for the KillStream gain effect in Loot Run
Allow to cancel the display of BossBar for trade unions/regions
Add Mobs' health display as Overlags
Add Scoreboard display as Overlags
Prioritize displaying the curse effect in Lootrun at the top of the Buff list and modify it to a different color and icon

**Comment by kristofbolyai** [comment]
Please move these to discord or feedback.wynntils.com

**Comment by Yurium7** [comment]
> 请将这些移动到 discord 或 feedback.wynntils.com

ok
