### ISSUE TITLE
Broken Dungeon keys do not get letter overlay

### ISSUE THREAD

**Issue by magicus** [Wynntils/Wynntils#253]
Like this:

<img width="387" alt="Screenshot 2022-08-08 at 01 43 24" src="https://user-images.githubusercontent.com/6209108/183315712-c5a71bd9-a0e1-482a-be37-af40dc6ff39f.png">

**Comment by HighCrit** [comment]
Those are broken broken dungeon keys, they're not supposed to be like that.

**Comment by magicus** [comment]
They might be very old. Are they unusable? Otherwise, we should tag them as non-broken broken keys, I think.

**Comment by kristofbolyai** [comment]
I think you can covert them to be usable, not sure if they are worth the effort. We parse keys using lore, not only item name.

**Comment by magicus** [comment]
Okay. I give up on this, then. :)
