### ISSUE TITLE
Directory could not be created if directory already exists

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#254]
We get the error `Directory /home/kristof/Artemis/fabric/run/wynntils/config could not be created` when we already have the directory.

**Comment by magicus** [comment]
Is this with my mkdirs fix? (https://github.com/Wynntils/Artemis/pull/245)

**Comment by kristofbolyai** [comment]
> Is this with my mkdirs fix? (#245)

Yes
