### ISSUE TITLE
[MapData] - Minimum visibility to render is slightly off, allowing hovering unrendered features

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#2548]
![image](https://github.com/Wynntils/Artemis/assets/49001742/ca4502c8-348e-4637-af90-e521d8aeff5d)

1 more zoom step
![image](https://github.com/Wynntils/Artemis/assets/49001742/95468a9e-abe5-4a20-b5e4-0aec8c029bac)

**Comment by kristofbolyai** [comment]
Also, I am not sure if we used to allow hovering features that were not 100% rendered. Maybe we should check that.

**Comment by magicus** [comment]
I think the old implementation also allows hovering on icons that are almost fully invisible. But I agree that it is no good.

We should probably set a cutoff at like 10% or 20% visibility. (We might need to check at what level of visibility it "feels" natural that you should be able to hover).

**Comment by kristofbolyai** [comment]
Essentially fixed by https://github.com/Wynntils/Artemis/pull/2550
