### ISSUE TITLE
Beta warnings are outdated

### ISSUE THREAD

**Issue by Tetro48** [Wynntils/Wynntils#2611]
Trying to join beta and then joining release version of Wynncraft results in a chat message. This shouldn't happen.
![image](https://github.com/Wynntils/Artemis/assets/76738929/98b19634-073c-4cad-ba68-0bb2f1ee0199)
Wynntils v1.2.27

**Comment by ShadowCat117** [comment]
Whenever someone gets around to fixing it we should probably have a reverse message as well, for joining beta on a release version stating that features may be broken

**Comment by kristofbolyai** [comment]
Absolutely!
