### ISSUE TITLE
Casting a spell on the 2.1 beta puts a large, opaque, blue vignette on the screen

### ISSUE THREAD

**Issue by WarpedVoxel** [Wynntils/Wynntils#2628]
1. Wynntils version: `v2.0.0-beta.1`
2. Mod loader: Fabric for Minecraft 2.21
3. Other mods were loaded when I first saw this. However, the vignette appears even when Wynntils is the only loaded mod.
4. Operating system: Archlinux
5. What I did: Logged onto the Wynncraft 2.1 Beta server; played the tutorial; cast a spell when the tutorial instructed.
6. What I expected to see: my full field of view.
7. What I saw instead: a huge, opaque, blue vignette.
![2024-07-06_20 08 17](https://github.com/Wynntils/Artemis/assets/56001368/02cad6aa-794e-4062-9570-5e58c7d17ea4)

**Comment by magicus** [comment]
As a workaround, you can disable spell casting vignettes for now.

**Comment by kristofbolyai** [comment]
Actually, this is fixed on latest beta :) It was a reoccurring world state bug, which I've also added a failsafe for, to render nothing, instead of having this bug.
