### ISSUE TITLE
Text isn't scaled when scaling overlays

### ISSUE THREAD

**Issue by HighCrit** [Wynntils/Wynntils#275]
![image](https://user-images.githubusercontent.com/35771251/183883949-3b915f87-e5fc-4fe9-87b8-08a9df85e6a8.png)

**Comment by kristofbolyai** [comment]
This is now possible to do in FontRenderer, but needs implementation on a per overlay basis.

**Comment by magicus** [comment]
This is a tricky one. Are we sure we want to do that? I seriously think that "font scaling" is a separate UI concern from "outline scaling" of overlays. 

To be clear: I agree that it should be possible to scale fonts. But it should not be part of rescaling the size of overlays. We will need a separate way to change font sizes. Perhaps using the scroll wheel in the overlay editor? Or a slider or other widget.

**Comment by kristofbolyai** [comment]
Technically, this is fixed, where it is needed. https://github.com/Wynntils/Artemis/issues/654 will track this.
