### ISSUE TITLE
Changelog could be better... Do you just generate it from commit summaries/issue titles?

### ISSUE THREAD

**Issue by Twisted-Code** [Wynntils/Wynntils#2769]
For instance, why do you have "skip CI] ([" in change log entries like this? I assume you tagged something to "skip continuous integration" and it paired up the wrong square brackets?
![image](https://github.com/user-attachments/assets/0afb3fbd-6b60-475a-8fe7-7d496874674c)
Most people, including myself since I am a novice at best at Java, will only be able to roughly infer what these class names mean.
![image](https://github.com/user-attachments/assets/831e8855-d517-4e04-8825-6035463935fb)

I was still able to get the gist of the changes, so don't misunderstand, the unexpected words just threw me for a loop when first trying to read the entries (this is my first time updating the mod since joining for Rekindled, woo).

**Comment by magicus** [comment]
You are correct; these are auto generated. Making a manually curated changelog would require too much effort; we don't have that kind of manpower in the development team.

We should strip the `[skip ci]` part, though. And the removed leading bracket is just weird.

**Comment by kristofbolyai** [comment]
I'll close this as it's been answered, and it's a question, not an issue.

**Comment by magicus** [comment]
Well, yes, but apart from the question there was also a bug reported. I opened #2771 to more clearly deal with that.

**Comment by kristofbolyai** [comment]
Yes, thank you.

**Comment by Twisted-Code** [comment]
Yes thanks for creating the follow-up. The mishandled tag was the main thing I intended to highlight with my question; I understand if you can't go into agonizing detail on every minor release' changelog! (Though a summary of anything major being added, when relevant, would be nice)
You might also consider trying (this word is operative, of course) to keep the PR titles layman-friendly, if you know they are going to be seen by people not as familiar with your code (or coding at all). But like really, just having a changelog ingame is better than most mods I've seen, so...

**Comment by magicus** [comment]
Unfortunately, we need to have PR titles that makes sense to us developers, and only secondary as changelog items.

However, bolyai usually posts a write-up in the discord whenever something of major interest is released.

**Comment by Twisted-Code** [comment]
Yeah that's fair enough, I suppose it already needs to balance being technical, specific and concise. I don't do a lot of development myself so I haven't even figured that balance out yet for my own projects.

Re: Discord: Is there a way to subscribe to/see this write up without having to join another discord server? E.g. a web hook (Perhaps using the "follow channel" feature)? I ask mostly out of curiosity, but also because I wish more cool projects were accessible in this way.

**Comment by magicus** [comment]
I think Discord allows you to "subscribe" to a channel on a different server; but I don't know the details. This bug report is not the right place for support about Discord though.

**Comment by Twisted-Code** [comment]
Fair enough, though it wasn't my choice of publishing method...
I have more to say but I think it would be better to follow up on it in another issue, or on discord if I feel so inclined. Probably at a later date as I don't want to let any of my pre-existing prejudices sneak into my reply.
