### ISSUE TITLE
When using abilities, 90% of the screen turns blue and a visual bug on the character selection scene. (1.20.2)

### ISSUE THREAD

**Issue by dzsoni1337** [Wynntils/Wynntils#2772]
I made screenshots according to the title.

![kép_2024-08-23_155043532](https://github.com/user-attachments/assets/04510913-4d49-4cc5-bc06-41261b1e5007)
![Uploading 2024-08-23_15.51.58.png…]()

**Comment by kristofbolyai** [comment]
1.20.2 is unsupported both MC version and Wynncraft wise. Update to 1.21.

**Comment by kristofbolyai** [comment]
Noting for developers that this has been fixed in 1.21, and even breaking Wynncraft changes can't bring this behavior back.

**Comment by dzsoni1337** [comment]
thanks
