### ISSUE TITLE
failed to share item

### ISSUE THREAD

**Issue by HazardEST** [Wynntils/Wynntils#2783]
pressing F3 on items with certain id's on them causes an error

for example, chained pixels with its % elemental defense id causes an error

also some items dont even show the error message, like the necklace "dogfight"

my guess is wynntils doesn't have up-to-date API or something

**Comment by kristofbolyai** [comment]
Hi, thanks for reaching out.

Please refer to my linked comment about info on 2.1 items. https://github.com/Wynntils/Wynntils/pull/2777#pullrequestreview-2258623609

Thank you.
