### ISSUE TITLE
When deleting a class, class selection screen doesn't show any indication of the occupied slot

### ISSUE THREAD

**Issue by Twisted-Code** [Wynntils/Wynntils#2784]
This can result in a situation where only 5 slots appear to be used but you still can't create another character. 
![image](https://github.com/user-attachments/assets/3ac70f12-3734-444e-b2cc-38e242e1d772)
Maybe it should display information about the in-progress deletion? I don't think there's any way I can see the deletion-in-progress, currently, without disabling the mod.

**Comment by ryanzhoudev** [comment]
Custom class selection is now gone due to new vanilla Wynn 2.1.1 selector.
