### ISSUE TITLE
[Feature Request] Ability to get the current area name

### ISSUE THREAD

**Issue by gousisme** [Wynntils/Wynntils#2794]
We only have "is in mapped area" but not the area name, would be great to have that to display on the hud

**Comment by ShadowCat117** [comment]
The `current_territory` function does that?
![image](https://github.com/user-attachments/assets/6c300c4a-6bc0-4232-a6eb-39248bd27d3d)

**Comment by gousisme** [comment]
But I'm standing in Detlas and it returns nothing?
![image](https://github.com/user-attachments/assets/f4c63a40-f61b-45dc-8788-e938d2209261)

**Comment by ShadowCat117** [comment]
It probably failed to download the territory info from the Wynncraft API which had some issues earlier as we use that to get the bounds for each area

**Comment by gousisme** [comment]
i just created a fresh instance to test it out, seems like the fuy.gg mod is the issue here

**Comment by Essentuan** [comment]
> i just created a fresh instance to test it out, seems like the fuy.gg mod is the issue here

Yeah I know abt this, unfortunately I have to wait for someone to log on before I can fix it. Hopefully It should be working better tomorrow.

**Comment by kristofbolyai** [comment]
> > i just created a fresh instance to test it out, seems like the fuy.gg mod is the issue here
> 
> 
> 
> Yeah I know abt this, unfortunately I have to wait for someone to log on before I can fix it. Hopefully It should be working better tomorrow.

Do you override a function, or the underlying model?
