### ISSUE TITLE
Party UI and Minimap Issue

### ISSUE THREAD

**Issue by sadsa993** [Wynntils/Wynntils#2808]
The first time I used the mod, the party UI appeared correctly, and I could see my friend in the party as well as on the minimap. However, on subsequent attempts, the party UI did not appear, and neither of us could see each other on the minimap. 
Both of us have the mod installed.

**Comment by kristofbolyai** [comment]
Our servers have some long-standing issues, this is not a bug with the mod. Unfortunately we can't do anything in the mod to fix this issue.
