### ISSUE TITLE
Profession XP is not updated when refining fails or alt resources are gathered

### ISSUE THREAD

**Issue by My4096** [Wynntils/Wynntils#2817]
When failing to refine common materials like Oak, or when gathering alternative resources such as Bamboo or Voidgloom, the Profession XP gained is not reflected in the XP Gain Message or in the overlays that use `prof_pct()` or `prof_xpm_raw()`.

In my environment, I tested gathering Starfish, Oak, Spruce, Voidstone, and Hemp. XP was reflected when refining succeeded, but not when refining failed. Additionally, XP was not reflected when gathering Abyssal Matter, Bamboo, Flerisi Tree, and Voidgloom. I have not tested Larbonic Geode due to insufficient Mining Level, but it is expected that XP will not be reflected for it as well.

Other information is as follows:
- Wynntils version: 2.1.1
- Mod loader: fabric-loader-0.16.2-1.21.1
- Other mods: None
- Operating system: Windows 10

**Comment by ShadowCat117** [comment]
I was finally going to look into fixing the alternate resources gathering fix for this but turns out it was fixed by the same pr :)
