### ISSUE TITLE
Chat clickables not always working

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#282]
https://media.discordapp.net/attachments/942564848330498048/1007264759449653288/unknown.png

**Comment by magicus** [comment]
There is a case in vanilla where this happens, just want to check this is not the case here. If this happens:
1) you get a link in chat
2) you talk to a NPC
3) after talking, the old "screen" is restored

In this case, the "restore" in 3 does not restore links.

WIth the NPC dialogue overlay, this problem should be avoided.

**Comment by magicus** [comment]
I saw this behavior myself. It was immediately upon login to a new world/class, when Wynntils dumps a whole lot of messages at once. Then they are sent as a multiline screen, but (apparently) with proper Component contents available. 

That means that I either need to make a function to split a massive Component constructor on line breaks (I'm *not* fond of writing that function!), or I need to find a way to encode Components into strings that does not lose any information (basically, finding a way to store hover and onClick data). This I've actually been thinking about for a while (it was needed for translation as well), and it seems like a more doable way, but it is still quite some effort.

I'll open a separate bug to track my thinking on the issue.

**Comment by magicus** [comment]
See https://github.com/Wynntils/Artemis/issues/292

**Comment by magicus** [comment]
I'm starting to think this might be TranslationsFeature that is responsible. Are you sure you have it turned off?

**Comment by kristofbolyai** [comment]
Tracking this in #292.
