### ISSUE TITLE
Bomb bell overlay not working, possibly because I'm in a guild?

### ISSUE THREAD

**Issue by Twisted-Code** [Wynntils/Wynntils#2834]
For some reason the bomb bell overlay stopped working for me. It was working fine a few days ago, but I think stopped working around the time I joined a guild for the first time. I suspect your code might be having issues reading the bossbar now that it alternates between territory info, guild info, and only after that any active bombs. Would really appreciate if y'all could look into this, as the new information is also making it harder for _me_ to read the bossbar.

**Comment by ShadowCat117** [comment]
I just tested the patterns and the boss bar bomb pattern still works, are you sure you haven't disabled that specific bomb type from the overlay or disabled it entirely  by accident?

**Comment by Twisted-Code** [comment]
It doesn't seem to be entirely disabled in my settings, and unless there is a keybind to disable it I'm not sure how I would have done so accidentally anyway.
Of course I could be misreading the settings GUI. What files and settings are relevant to disabling the feature, I could CTRL + F to double check?

**Comment by Twisted-Code** [comment]
Seems to be working again. Weird... I am hesitant to close this issue since I suspect it will happen again. Any idea how it could've gone from working to not working to working?

**Comment by Twisted-Code** [comment]
I haven't seen this in almost 2 months (since my previous comment), so I'm going to assume it was some sort of fluke.
