### ISSUE TITLE
Placing items in misc bucket & bookshelf with inventory sync enables tries to pick up another item

### ISSUE THREAD

**Issue by ShadowCat117** [Wynntils/Wynntils#2888]
Whilst in the misc bucket or bookshelf containers, placing an item either into the container or your inventory displays the "You cannot place this item in this bank!" message even when placing items that are valid for that container. The issue only occurs whilst the Improved Inventory Sync feature is enabled

https://github.com/user-attachments/assets/07fefea0-4ea8-45b2-a034-a1b6c0542c5a

**Comment by ShadowCat117** [comment]
@phantamanta44 Do you want to have a look into this?

**Comment by magicus** [comment]
@phantamanta44 This was a perfect showcase of why we are so keen on being able to disable that kind of functionality. ;-)

**Comment by phantamanta44** [comment]
argh, i forgot housing existed
