### ISSUE TITLE
Item Guess cannot work properly

### ISSUE THREAD

**Issue by Yurium7** [Wynntils/Wynntils#2890]
When Use 
[ItemBorders-1.21-fabric-1.2.5]
[LegendaryTooltips-1.21-fabric-1.4.11]
[Prism-1.21-fabric-1.0.9]
[Iceberg-1.21-fabric-1.2.5]
Item prediction cannot work properly

![image](https://github.com/user-attachments/assets/8e6a73a3-9df0-47bd-8607-3eface6459b0)
![image](https://github.com/user-attachments/assets/af0b1256-f845-4936-a795-b37643f040bc)

**Comment by ShadowCat117** [comment]
It's an issue with LegendaryTooltips and its dependencies. Remove Iceberg, Prism and LegendaryTooltips.

[Issue on Iceberg](https://github.com/AHilyard/Iceberg/issues/75)

**Comment by Yurium7** [comment]
> 这是 LegendaryTooltips 及其依赖项的问题。删除 Iceberg、Prism 和 LegendaryTooltips。
> 
> [Iceberg 上的问题](https://github.com/AHilyard/Iceberg/issues/75)

Can this bug be fixed to make this feature work properly when using the above mod?

**Comment by ShadowCat117** [comment]
Fixed in https://github.com/Wynntils/Wynntils/pull/2956
