### ISSUE TITLE
com.wynntils.models.beacons.type.BeaconKind

### ISSUE THREAD

**Issue by Ooshkar** [Wynntils/Wynntils#2915]
The 2.3.10 update gives me this error, i fixed it by downgrading to 2.3.9

The error i am getting is: 
Caused by: com.google.gson.JsonIOException: Interfaces can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Interface name: com.wynntils.models.beacons.type.BeaconKind 

I belive this error could be caused by "Hide original activity beacon & marker ([#2907](https://github.com/Wynntils/Wynntils/issues/2907)) ([74634e7](https://github.com/Wynntils/Wynntils/commit/74634e7c96553bff3726c04bc7101c160ad380cc))"

Hope this gets fixed soon 👍 

Full Logs:
[full dump wynn.txt](https://github.com/user-attachments/files/17340242/full.dump.wynn.txt)

**Comment by magicus** [comment]
This is fixed by #2916 which is present in 2.3.11. Just upgrade and you'll be fine.
