### ISSUE TITLE
Hide unused (or unusable) Wynncraft server-side commands

### ISSUE THREAD

**Issue by magicus** [Wynntils/Wynntils#293]
We should intercept the Brigadier construction and block these commands:

```
bungee
galert
gcountdown
glist
gsend
perms
pfind
plist
pwlist
sendtoall
sparkb
sparkbungee
wcl
wynnproxy
```

**Comment by Incompleteusern** [comment]
Isn't `glist` for guild list? `plist` and `pfind` also seem to be user commands. Might be wrong though.

**Comment by magicus** [comment]
Do they seem to work for you?

Afaict, the guild commands are all subcommands to `/guild`:
```
Guild Commands (Recruit):
/g [message] - Send a guild message
/guild manage - Opens guild management
/guild territory - Opens territory view
/guild join [tag] - Joins a guild by tag
/guild leave - Leaves the guild
/guild list - Lists guild members
/guild leaderboard - Shows guild leaderboard
/guild stats - Shows guild stats
/guild xp [amount] - Sets XP contribution
/guild log - Shows the guild log
/guild rewards - Redeem your objective reward if available
```

**Comment by magicus** [comment]
Btw, the next step (or actually a separate step) is to add tab-expansion help for working wynncraft commands. I'd like to do that, too.

**Comment by Incompleteusern** [comment]
That'd be cool

**Comment by Incompleteusern** [comment]
Should this be closed? @magicus

**Comment by magicus** [comment]
Yes, thanks. Fixed by https://github.com/Wynntils/Artemis/pull/307.
