### ISSUE TITLE
[request] Remove/hide Wynncraft coordinates

### ISSUE THREAD

**Issue by K0-RR** [Wynntils/Wynntils#2942]
![Screenshot_20241022_123950](https://github.com/user-attachments/assets/b7d00e7a-4b56-4ac6-956e-13d336054aa9)

Since Wynntils already shows the coordinates above the minimap, and the serwer-side ones are being drawn over the F3 menu, obsuring the memory usage

**Comment by kristofbolyai** [comment]
It's already a config to hide it.
