### ISSUE TITLE
Connection Failed while Transferring to the Server. 

### ISSUE THREAD

**Issue by ilykookie** [Wynntils/Wynntils#2954]
Hi, I am on MacOS 14.3 and everytime I try to connect to Wynncraft using Wynntils I am presented with the error of it repeatedly trying to connect to the server and it failing with "Connection failed while transferring to the server; Failed to log in: RateLimiter disallowed request"

This occurs for neoforge and fabric.

**Comment by kristofbolyai** [comment]
This is a Wynncraft issue. Please report it to them, if the issue is still unsolved.
