### ISSUE TITLE
Auto progressing NPC dialogue 

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#297]
Thing is, we have these NPC dialogues where they "auto-progress", meaning there is no need / no way to progress with "SHIFT". Can we make the `NpcDialogEvent` somehow indicate this? (for example King's Recruit quest)

**Comment by magicus** [comment]
King's Recruit is the very first quest, right? That makes it easy for me to check it out.

**Comment by kristofbolyai** [comment]
> King's Recruit is the very first quest, right? That makes it easy for me to check it out. 

Yes it should be. Although it might be very scripted on Wynn's side so testing will be required on other quests.

**Comment by magicus** [comment]
Closing this as dup of https://github.com/Wynntils/Artemis/issues/334 since that where the design discussion ended up (even though this was prior).
