### ISSUE TITLE
Ophanim bar does not seem to be tracking healing percentage correctly

### ISSUE THREAD

**Issue by Twisted-Code** [Wynntils/Wynntils#2974]
I'm not sure exactly what changed (guessing something on Wynn's side; maybe something with how they recently changed the speed of Orphion's Pulse) but my Ophanim bar does not seem to match the amount of healing I know I am doing between myself and my orbs. I've got like 5 orbs (Each of which should have around 1/3 of my 7K health), get them down to red, and use sigil of terror to eat 99% of my health... healing from this point only brings the percentage according to the overlay up to around 10%, but is enough to activate Sunflare! Something is obviously wrong.

**Comment by ShadowCat117** [comment]
The overlay just copies the values from the default boss bar, doesn't do any extra calculations so if you think it's not giving the correct values then turn on the original boss bar and compare the values. If there is any difference we can look into fixing it but this shouldn't be an issue

**Comment by ShadowCat117** [comment]
Have you been able to check if the original boss bar displays the same data or not?

**Comment by ShadowCat117** [comment]
Going to assume the issue was on Wynn's end and will be fixed in the upcoming patch
![image](https://github.com/user-attachments/assets/8c732c89-c0e6-4d87-a2f5-f6080c116f54)
