### ISSUE TITLE
settings export tooltip is wrong

### ISSUE THREAD

**Issue by Twisted-Code** [Wynntils/Wynntils#2987]
It should say "to" not "from". Need to bake your copy-pastries a bit longer /lh
![image](https://github.com/user-attachments/assets/da2d31e3-ea01-46a2-bdec-e57ff11b9d29)

I think I can PR this since so trivial; [it's pulling the string from here](https://github.com/Wynntils/Wynntils/blob/main/common/src/main/resources/assets/wynntils/lang/en_us.json#L2546), assuming you don't have redundant strings elsewhere. In fact, I'll probably have a fix committed to my fork by the time you read this. Anything I should know before PRing or does [CONTRIBUTING.md](https://github.com/Wynntils/Wynntils/blob/main/CONTRIBUTING.md) cover everything?

**Comment by ShadowCat117** [comment]
Fixed in https://github.com/Wynntils/Wynntils/pull/2988
