### ISSUE TITLE
Quest Tracker doesn’t update half the time

### ISSUE THREAD

**Issue by PostageBread** [Wynntils/Wynntils#2996]
Whenever a quest moves on to the next stage sometime the beacon and quest still say the old thing. I have to reenable the quest to fix it. I updated to latest version and am still having the problem :0

**Comment by ShadowCat117** [comment]
`/toggle autotracking`

**Comment by PostageBread** [comment]
> `/toggle autotracking`

Why is it off by default?

**Comment by ShadowCat117** [comment]
Absolutely no idea

**Comment by PostageBread** [comment]
> Absolutely no idea

Thanks for the quick reply. Do you know why if it’s off that it still sometimes tracks the quest right. Someone told me it might happen when the next part of the quest doesn’t have coordinates but I’ve found out it’s not that.

**Comment by ShadowCat117** [comment]
It only occurs for the first stage, so if you track a quest you haven't started then start that quest it will not update until you untrack and retrack it. Any other stage after that it works as normal

**Comment by PostageBread** [comment]
Ah makes sense thank you <3
