### ISSUE TITLE
Mixin specification is incorrect

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#302]
`[19:59:53] [Render thread/INFO] (FabricLoader/Mixin) wynntils.mixins.json:accessors.MinecraftAccessor from mod wynntils->@Accessor[FIELD_GETTER]::getFps()I should be static as its target is`

**Comment by magicus** [comment]
I sneaked in a fix in https://github.com/Wynntils/Artemis/pull/306
