### ISSUE TITLE
Combine auto progress with NPC dialogue overlay

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#304]

**Comment by magicus** [comment]
You mean if the overlay is disabled while it is showing a dialogue? What did you expect to happen? 😮  The next dialogue screen sent should work as normal. Does it not?

**Comment by kristofbolyai** [comment]
Nothing appeared in chat.

**Comment by kristofbolyai** [comment]
It might be because of my PR though, but I doubt. The thing should not depend on dialog extraction being disabled, but rather if it is being "consumed". See #305.

**Comment by magicus** [comment]
I'm still not sure what you mean, though. Did all NPC chat disappear, like, forever and always, if you do not have the overlay enabled? Or did you disable the overlay while in the middle of a dialogue, and that messed up that current NPC interaction?

**Comment by kristofbolyai** [comment]
Iirc, if you do not have the overlay enabled, but the feature still enabled dialog extraction, then messages wont be sent in chat (and since we don't have an overlay, we cannot see it). We would need to look at the users of the NPC dialogue, and send it to chat if no-one is using it.

**Comment by magicus** [comment]
Agree, I thought this was the case. If it's not, then it is definitely a bug. I'll look more closely into it.

**Comment by magicus** [comment]
I fail to reproduce by turning on and off the overlay and turning on and off the actual feature. I'll look into the code to see if there is something else that can cause us to lose dialogues.

**Comment by magicus** [comment]
Yes, looks like this can happen if you turn on auto progress but not NPC overlay.

**Comment by magicus** [comment]
I think I would like to solve this by folding the auto progress functionality into the NpcOverlay feature itself. I have a hard time seeing how the autoprogress could ever work fine if we do not pick out the dialogue and present it in an overlay. And I frankly doubt that anyone would ever want to do that.

**Comment by magicus** [comment]
@kristofbolyai There is also a bug in auto progress, where it got into a bad state of being disabled, but still showed "0 seconds left" all the time. I triggered it by enabling and disabling Npc overlay, auto progress, etc, in some random order.

![image](https://user-images.githubusercontent.com/6209108/187198567-b3ff4f6a-671a-4038-895c-9116309093c0.png)

**Comment by kristofbolyai** [comment]
> @kristofbolyai There is also a bug in auto progress, where it got into a bad state of being disabled, but still showed "0 seconds left" all the time. I triggered it by enabling and disabling Npc overlay, auto progress, etc, in some random order.
> 
> ![image](https://user-images.githubusercontent.com/6209108/187198567-b3ff4f6a-671a-4038-895c-9116309093c0.png)

If you merge the two features, this should not be a problem?

**Comment by magicus** [comment]
I think so.

**Comment by kristofbolyai** [comment]
Fixed with #366
