### ISSUE TITLE
Item to compare persists through a relog but doesn't draw circle

### ISSUE THREAD

**Issue by HighCrit** [Wynntils/Wynntils#332]
![image](https://user-images.githubusercontent.com/35771251/185187113-7af6ae79-4ea9-4e45-8836-048cdca58d97.png)

**Comment by kristofbolyai** [comment]
And it also self compares..

**Comment by magicus** [comment]
I can imagine this being a problem for many features. If you save some kind of state, it should be reset if you leave/enter a world. I wonder if we can find a common solution to this, or if we just need to remember to listen to world state change events, and reset needed variables manually.
