### ISSUE TITLE
Using mouse buttons as keybinds doesn't work in inventories

### ISSUE THREAD

**Issue by HighCrit** [Wynntils/Wynntils#333]
![image](https://user-images.githubusercontent.com/35771251/185187371-7ded30a5-c521-45fd-86df-37a828ad32dd.png)
In the screenshot I've set a spare mouse button to select items to compare. But this doesn't work.

**Comment by kristofbolyai** [comment]
This is related to non keyboard buttons in inventories.

**Comment by magicus** [comment]
Yes, to get that to work probably means we have to fix so inventory keybinds use the Minecraft vanilla method. Which apparently has been broken.

**Comment by kristofbolyai** [comment]
When fixing this, we also need to fix same key keybinds not working, even when they are not used in the same context. (Space keybind in inventory or a screen makes jump not work)
