### ISSUE TITLE
NPC dialogue overlay should also catch "non-screen" dialogue

### ISSUE THREAD

**Issue by HighCrit** [Wynntils/Wynntils#334]
![image](https://user-images.githubusercontent.com/35771251/185193097-2e84180c-23a4-4beb-a0cf-7402177d83c2.png)
Multiple dialog lines during the Hero of Gavel quest are not shown in the overlay but in chat.

**Comment by HighCrit** [comment]
Don't know if this is related but some dialog still spams the chat with grayed text:
![image](https://user-images.githubusercontent.com/35771251/185194772-6b5b95ca-f270-45e6-bafe-5661ff961fdb.png)
![image](https://user-images.githubusercontent.com/35771251/185196285-9ac09e6e-fe79-4b01-bb6f-31b0c31b639a.png)

**Comment by kristofbolyai** [comment]
> Don't know if this is related but some dialog still spams the chat with grayed text:
> 
> ![image](https://user-images.githubusercontent.com/35771251/185194772-6b5b95ca-f270-45e6-bafe-5661ff961fdb.png)
> 
> ![image](https://user-images.githubusercontent.com/35771251/185196285-9ac09e6e-fe79-4b01-bb6f-31b0c31b639a.png)
> 
> 

Another bug on that image is that the first formatting code is lost. (as the white should be gray) @magicus

**Comment by magicus** [comment]
@HighCrit Is this the kind of NPC chat that does not require you to press sneak to continue?

I have deliberately not moved those to the NPC overlay. I'm not sure how to handle them, really. Show them there anyway, but with a timeout? Require sneak anyway to close the overlay?

**Comment by kristofbolyai** [comment]
@magicus you can test if it is with King's Recruit (#297)?

**Comment by kristofbolyai** [comment]
(#297 and this is duplicate mostly.)

**Comment by magicus** [comment]
Maybe we have just been talking past each other. I know NPC dialogues without a "screen" (that is, "press sneak to continue") will not be captured by the overlay (nor the chat manager). It is just not implemented. I thought the "auto progress" in #297 meant your feature to automatically send sneak.

It sounds like these two bugs are duplicates, yes.

The problem here is not so much a technical issue of matching the NPC dialog, as a UX issue. I can throw up the dialogue on the overlay, but when should I remove it?

**Comment by kristofbolyai** [comment]
I think show until next dialogue is sent? That will be fine in most cases.

**Comment by magicus** [comment]
That can be for quite some time. Remember quests like the broken iron golem? When you start enter the cave, the golem starts shouting stuff about it remembering (or not remembering) it's name. For each step you progress, more info is given. The same idea is used in other quests as well.

**Comment by kristofbolyai** [comment]
Then until next one or shift or auto progress. I think ironically this one is the easiest to code.

**Comment by magicus** [comment]
I also worry that it will cover the screen in a situation where you might need to be able to see clearly to fight monsters.

Or maybe I just worry too much. I can probably re-use the auto progress feature code to get the timing right. If we can quickly hide it with sneak it's probably okay.

I would like to see a way to show NPC dialog history, though. The Wynncraft vanilla variant is just a mess. If we get the real NPC dialogs, we could should them more clearly. Hm... That could be as easy as a command that just dumps the NPC dialog history to the chat.

**Comment by magicus** [comment]
This will probably by, finally, solved by https://github.com/Wynntils/Artemis/pull/435.
