### ISSUE TITLE
/wynntils should have feature and config commands as sub-commands

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#348]
I agree that these commands can be on their own, but it is weird not to have them as sub-commands as well.

**Comment by magicus** [comment]
Is that really so? For all other `/wynntils` things, it is more about like the "meta" of the Wynntils mod, like discord, version, etc. `/feature` and `/config` is like core functionality of the mod.

It's like we should have `/wynntils lootrun`. 

But if you think that is a good idea, and that basically all of our commands should be able to be prefixed with `/wynntils` as well, I don't know really what to say. If it is important to you, well, then we fix it. But if that is the case, we should be consistent and do so for all our commands.

**Comment by kristofbolyai** [comment]
I might have used /wynntils config too many times during development... Although, it does feel weird to not have a `/wynntils feature` command, as I think it expresses that I want to do something with a Wynntils feature. All in all, it does not hurt to have them IMO.

(I also agree that we can just do this for all commands to be consistent)

**Comment by Incompleteusern** [comment]
if we do this for all commands we would have `/wynntils wynntils`
