### ISSUE TITLE
Minimap Overlay covers other vanilla features like tab list and f3

### ISSUE THREAD

**Issue by Incompleteusern** [Wynntils/Wynntils#355]

**Comment by kristofbolyai** [comment]
likely solved by rendering on RenderEvent.Pre for GUI ElementType

**Comment by Incompleteusern** [comment]
Yeah going to make a pr after testing

**Comment by Incompleteusern** [comment]
![image](https://user-images.githubusercontent.com/58920010/187092357-d8145ef9-6d5d-4ff0-90d0-0a07f1ddf298.png)
Minimap is now dark underwater

**Comment by magicus** [comment]
Some RenderState we need to reset?

**Comment by kristofbolyai** [comment]
Should we move Post  to before rendering F3 screen? Or is it not really Post?
