### ISSUE TITLE
objectives unknowingly freeze

### ISSUE THREAD

**Issue by IngeniousCoder** [Wynntils/Wynntils#386]
![image](https://user-images.githubusercontent.com/29097583/188695617-b929bc36-c3f8-42cf-ad39-2c1ea08c08b3.png)
Objective froze at 105/140, suddenly Complete notification appeared, I checked and claimed rewards, objective is done but objective counter is not working.

**Comment by Incompleteusern** [comment]
What modloader are you using? Is this the latest build?

**Comment by IngeniousCoder** [comment]
This is 1.18.2 Wynntils build 283

**Comment by IngeniousCoder** [comment]
[latest.log](https://github.com/Wynntils/Artemis/files/9499329/latest.log)
Didn't see anything from Wynntils relating to the Objectives but worth uploading.

**Comment by magicus** [comment]
I've seen something similar once. I think the objective manager got stuck in a bad state.

**Comment by kristofbolyai** [comment]
#407 should have fixed this. Reopen if it occurs again
