### ISSUE TITLE
WebManager (sometimes) does not use caches

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#401]

**Comment by magicus** [comment]
Why do we even have an API that allows us not to cache? We should just have a single way to download resources, and that should require us to set a cache path.

**Comment by kristofbolyai** [comment]
Sometimes, we don't need caching, like territory api.

**Comment by magicus** [comment]
But then we should have a `NonCachingResource` or whatever, so it's clear we're doing something potentially bad.

**Comment by kristofbolyai** [comment]
> But then we should have a `NonCachingResource` or whatever, so it's clear we're doing something potentially bad.

Yeah... This system was pretty much copied from legacy

**Comment by magicus** [comment]
I know. That is kind of both good and bad. I've tried to copy code from Legacy, instead of rewriting, at times. It is not always up to par with the rest of Artemis in terms of standard. Otoh, it is a quick way to gain functionality.
