### ISSUE TITLE
Horse not auto-mounting

### ISSUE THREAD

**Issue by Konglomneshued** [Wynntils/Wynntils#412]
I have a friend using Artimes and he said he is able to automount his horse with the keybind he set.  My experience has been that it summons the horse but I do not mount it.  I wanted to post an issue here, I don't know if it's a bug or if another mod is contributing to this.

If you need any more information I will be happy to provide it.

I am using 1.18.2 Fabric with Artemis 1.1.0+301.MC1.18.2 and several other mods for perfomance and immersion.

**Comment by kristofbolyai** [comment]
This is likely happening due to 2.0 changes, I;ve remember someone saying something similar.

**Comment by Konglomneshued** [comment]
I'm going to try the latest version which just came out today.

**Comment by Konglomneshued** [comment]
It's not working for me on 302 either.

**Comment by kristofbolyai** [comment]
> I'm going to try the latest version which just came out today.

It fixed an issue with awakened bar, so it won't change.

**Comment by Konglomneshued** [comment]
Somehow the issue resolved itself.
