### ISSUE TITLE
Improve `WynntilsMod#handleExceptionInEventListener` to identify model class

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#449]
Currently it only identifies features.

**Comment by magicus** [comment]
You mean like just identify? Because we can't really turn off models. All kind of things will start to break in features if we do.

**Comment by kristofbolyai** [comment]
We could turn off features dependant on the model. Also, my original idea was just "Exception in x model" (as it currently does not tell that).

**Comment by magicus** [comment]
Telling you the model is perfectly fine. Turning off features as a result of a failing model will require some elaborate core structure support.

**Comment by kristofbolyai** [comment]
Hm. This is probably not that easy to do, not worth the time.

**Comment by magicus** [comment]
Yeah, if we have a failure in a model, we need a crash report. There is nothing we can disable for the user to continue running.
