### ISSUE TITLE
AWT Problems on Mac (Item Screenshot Feature not working)

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#455]

**Comment by kristofbolyai** [comment]
See https://github.com/Wynntils/Artemis/pull/456

**Comment by kristofbolyai** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/5591#issuecomment-470805491

**Comment by magicus** [comment]
It seems impossible to solve item screenshotting on macOS without use of some 3rd party library. The mod now tells the user this is not supported. I will close this.
