### ISSUE TITLE
Functions also need crash protection

### ISSUE THREAD

**Issue by magicus** [Wynntils/Wynntils#471]
We don't want to bring down the entire InfoBoxOverlay if a single function misbehaves

**Comment by magicus** [comment]
Also, we should consider changing so FunctionManager do not call functions unless we are connected to the Wynncraft server.

**Comment by magicus** [comment]
Note that #584 only solves the first part; functions are still not guarded by being connected to the wynncraft server.

**Comment by kristofbolyai** [comment]
> Note that #584 only solves the first part; functions are still not guarded by being connected to the wynncraft server.

I forgot that we have the command, and not only overlays. But wait.. Commands are only registered on wynn, same with overlay? Do we need this?

**Comment by magicus** [comment]
Maybe we don't. It's just a bit of double safety I guess. (In Sweden, there is an expression of "wearing both suspenders and a belt")

**Comment by kristofbolyai** [comment]
IMO if we ever get to call a function while not on wynn, we messed up smth earlier.

**Comment by magicus** [comment]
Ok, I understand that position. Let's go with it.
