### ISSUE TITLE
Dungeon Keys Purchase not showing accurately in TM

### ISSUE THREAD

**Issue by IngeniousCoder** [Wynntils/Wynntils#501]
Similar to #324 ,

![image](https://user-images.githubusercontent.com/29097583/193630294-261dc1a3-070e-477a-9420-3ecbb3cd0912.png)

**Comment by Incompleteusern** [comment]
My favorite dungeon of 1

**Comment by IngeniousCoder** [comment]
would've preferred dungeon 999 :)

~~actually have not tested if the number > 9, might be worth testing~~

**Comment by Incompleteusern** [comment]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/58920010/193728647-de4f0f5a-8386-442c-b43e-b25ae0250b5e.png">

**Comment by IngeniousCoder** [comment]
![image](https://user-images.githubusercontent.com/29097583/193994424-44d49503-b7a3-4ac1-818a-fd5c96077d4c.png)

Happening to non-corrupted variants too

**Comment by Mcrtin** [comment]
Now they aren't even recognized as scrolls anymore in the tm buy screen and in the collect screen (see picture) which is probably due to the "new" annotation system
![image](https://github.com/Wynntils/Artemis/assets/66840021/5033e0ae-1204-45b5-9b12-92e43094e5be)

**Comment by SpaceMonkeyy86** [comment]
I'm going to try and fix this
