### ISSUE TITLE
Artemis minimap circle mask overrides Wynnlib side indicator 

### ISSUE THREAD

**Issue by Incompleteusern** [Wynntils/Wynntils#528]
Besides being a conflict, this is also indicative that our depth mask code isn't well enough.
![image](https://user-images.githubusercontent.com/58920010/194739776-f49c4903-d5d3-4e47-b226-73dbdd35b4f1.png)

**Comment by magicus** [comment]
Is Wynnlib having what is effectively their own overlays? If wo, we could consider submitting a PR that implements an "API" for Wynnlib so we a) at least could know about their screen coordinate, and b) potentially also modify them. If the route including b) would be accepted, then we could make a "proxy overlay" that allows us to adjust the Wynnlib overlays as well. If only a) is accepted, we can at least show in the overlay placement screen where immovable info boxes are.

**Comment by Incompleteusern** [comment]
The main problem here is with the depth mask not working well enough imo, and moving their overlay is a hacky solution.

**Comment by magicus** [comment]
But if we both write to the same location on the screen, the results will be messy regardless of depth mask. Or am I misunderstanding something here?

**Comment by Incompleteusern** [comment]
Their text rendering is fairly standard
