### ISSUE TITLE
Transformer configuration

### ISSUE THREAD

**Issue by Incompleteusern** [Wynntils/Wynntils#529]
Most properties (skill point color) lack a proper way to enable/disable them

**Comment by magicus** [comment]
There might be a simple fix for this, but I'm also thinking this is indicative that we need to disengtangle the itemstack logic.

**Comment by kristofbolyai** [comment]
Is this still an issue (that we want to fix)? What do you think @magicus?

**Comment by magicus** [comment]
It is phrased based on the previous architecture. If there still is a problem, it needs to be described in what needs changing right now. Item rarity color can e.g. be selected by the user.
