### ISSUE TITLE
MinecraftSchedulerManager should not expose queue

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#660]
I would do this now but Jcenter is down again and I can't be bothered working with offline gradle mode. This waits :)

**Comment by Incompleteusern** [comment]
The current usage of `MinecraftSchedulerManager` can be removed and replaced with a simple `Delay` of one tick that opens the screen afterwards.

**Comment by kristofbolyai** [comment]
> The current usage of `MinecraftSchedulerManager` can be removed and replaced with a simple `Delay` of one tick that opens the screen afterwards.

No. MinecraftSchedulerManager is important when you have to be on the correct thread, the game thread. Otherwise certain actions will fail.

**Comment by Incompleteusern** [comment]
It worked in legacy, but fair enough.

**Comment by kristofbolyai** [comment]
> It worked in legacy, but fair enough.

1.12.2 didnt use threads for render and game, like MC does now
