### ISSUE TITLE
Crash with CreativeCore

### ISSUE THREAD

**Issue by ghost** [Wynntils/Wynntils#665]
### Version

v0.0.1-alpha.19

### Brief Description

When using Wynntils Artemis and "recent" versions of 1.18.2 CreativeCore the game crashes during the initializing game phase

Although the crash is avoidable by using older versions of CreativeCore, I figured to leave it here for "documentation purposes"

### Steps to Reproduce

Have these mods in the mods folder:
[wynntils-0.0.1-alpha.19-fabric](https://www.curseforge.com/minecraft/mc-mods/wynntils/files/4074656)
[fabric-api-0.66.0+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4073282)
[CreativeCore_FABRIC_v2.6.12_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3827354)

Fabric Version 0.14.9

Launch the game and it will then crash during the games initialization

_Note:_
_This crash "seems to only happen" for all versions of CreativeCore between (inclusive):_
_[CreativeCore_FABRIC_v2.6.5_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3736276) to [CreativeCore_FABRIC_v2.6.12_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3827354)_

_Versions of [CreativeCore_FABRIC_v2.6.4_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3735159) and below do not seem to have this error_

### Crash Report

[crash-2022-11-08_22.03.24-client.txt](https://github.com/Wynntils/Wynntils/files/9967028/crash-2022-11-08_22.03.24-client.txt)

### Installed Mods

[wynntils-0.0.1-alpha.19-fabric](https://www.curseforge.com/minecraft/mc-mods/wynntils/files/4074656)
[fabric-api-0.66.0+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4073282)
[CreativeCore_FABRIC_v2.6.12_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3827354)

**Comment by magicus** [comment]
If this is due to CreativeCore doing too much weird stuff, I don't think we can (or should) fix it. But we should verify if it is any of our mixins (you know which I mean -- the prime suspects! ;-)) that are getting things messed up.

A plausible solution to this bug is also just to document this as a known incompatibility. But I'd really like to see *some* investigation before that.

**Comment by kristofbolyai** [comment]
> If this is due to CreativeCore doing too much weird stuff, I don't think we can (or should) fix it. But we should verify if it is any of our mixins (you know which I mean -- the prime suspects! ;-)) that are getting things messed up.
> 
> 
> 
> A plausible solution to this bug is also just to document this as a known incompatibility. But I'd really like to see *some* investigation before that.

CreativeCore fabric ports seems to have a dummy forge event bus impl for whatever reason. And it then conflicts with ours

**Comment by magicus** [comment]
Ah, it's a forge bus conflict. Hm. 

If they don't use their event bus, maybe file a bug report on them and ask if they can remove it..?

**Comment by kristofbolyai** [comment]
While we are not on latest MC, this is likely gonna be a wontfix from them.

**Comment by kristofbolyai** [comment]
Okay. I looked at CreativeLoaderFabric (CreativeCore Fabric). What they do is weird, even coming from us, who are using Forge's event bus on fabric. Since they are essentially overwriting Forge packages/classes, it makes our legitimate Forge Event Bus fail and crash. We can't do anything to fix it. This is a problem with CreativeCore and a fix needs to come from them.

**Comment by magicus** [comment]
@kristofbolyai Can we at least document this known incompatbility somewhere?

**Comment by kristofbolyai** [comment]
> @kristofbolyai Can we at least document this known incompatbility somewhere?

Yeah, we need to add this to README
