### ISSUE TITLE
/wynntils update should check if the latest version is already downloaded before downloading again

### ISSUE THREAD

**Issue by imIrony** [Wynntils/Wynntils#672]
I downloaded Artemis 10 times!
![image](https://user-images.githubusercontent.com/12867627/201447992-f05d05fe-0cac-4563-b77f-8d8bf6393a5b.png)

**Comment by Incompleteusern** [comment]
that's a lot of times.

However, this runs a command (`/wynntils update`) so it would be odd to fix, other than more checks to only download once

**Comment by kristofbolyai** [comment]
Log?
