### ISSUE TITLE
Pfinder party join message not recognized by hades

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#682]
![image](https://user-images.githubusercontent.com/49001742/201544056-6b9c87c4-35a7-49ca-8525-3c5dd2d58ea7.png)

**Comment by Incompleteusern** [comment]
also is that a nickname

**Comment by kristofbolyai** [comment]
no
![image](https://user-images.githubusercontent.com/49001742/201544146-4ff8cd3f-f3f5-478e-8cb3-3aa6edf77a38.png)
