### ISSUE TITLE
XP percentage and map issue (for me and some ppl I've talked with)

### ISSUE THREAD

**Issue by TNitroo** [Wynntils/Wynntils#687]
Hi there. I'm new to github, so would appreciate if you wouldn't be mad, that I doesn't even know where to put this request or how should I call this.
So, the thing is that in the newest version, there is no xp percentage, but was able to make one myself with the info boxes, but its not that good as it is in the normal wynntils for 1.12, so I would appreciate if you could integrate one.
And second, would be good if the map was like the in the normal wynntils. With this, I mean the easiness to share coordinates with others just by clicking with shift right click on the blue arrow and to be able to just click on the coordinates, so it pins immediately the place that the coordinates are for. Would really appreciate that if you could integrade these features and then it would be a perfect mod in my opinion.

**Comment by kristofbolyai** [comment]
Middle click on map to put a waypoint. Also, suggestions are not meant to be here. So if you want to do feature suggestions, post them there (although we already know it is missing). 

I will be closing this as Github issues are meant to be tracking bugs.

**Comment by TNitroo** [comment]
Rendben, bocsi a kellemetlenségért. Mint mondtam, ez az első alkalom, hogy használom a githubot :'D
Esetleg, lehet tudni, hogy mikor lesznek ezek a dolgok betéve a modba?

**Comment by kristofbolyai** [comment]
> Rendben, bocsi a kellemetlenségért. Mint mondtam, ez az első alkalom, hogy használom a githubot :'D
> 
> Esetleg, lehet tudni, hogy mikor lesznek ezek a dolgok betéve a modba?

Nem tudom

**Comment by magicus** [comment]
Kérjük, használjon angol nyelvet a Githubon, köszönöm. :-)
