### ISSUE TITLE
Classic button on Icons

### ISSUE THREAD

**Issue by DonKolia** [Wynntils/Wynntils#688]
### Version

1.12.2 :)

### Brief Description

If u click in classic button, client crash

### Steps to Reproduce

In the menu "M".
Configure Markers
If u click in classic button, client crash. 

### Crash Report

https://paste.ee/p/TBbNz

### Installed Mods

Wynntils-MC1.12.2-v1.15.0.jar

**Comment by magicus** [comment]
The 1.12 version of Wynntils is no longer supported. We will only fix crashes that prohibit all game play. Instead, switch to the new "Artemis" version for 1.19+.
