### ISSUE TITLE
Wynntils interfering with scoreboards on non-Wynncraft servers

### ISSUE THREAD

**Issue by P0keDev** [Wynntils/Wynntils#71]
Most likely caused by `FixPacketBugsFeature` always being active regardless of whether the user is actually on Wynncraft.

Example of the effect on Hypixel - scoreboard is completely blank when it should contain various bits of game info:
![image](https://user-images.githubusercontent.com/3767283/169628891-68f5ac72-5615-4c35-9787-312c1e089f42.png)

**Comment by Incompleteusern** [comment]
Joining hypixel with artemis/wynntils is inherently risky. But other than that, this implies a problem with the impl

**Comment by P0keDev** [comment]
> Joining hypixel with artemis/wynntils is inherently risky.

What makes you say this? Legacy Wynntils disables all game-altering features if you're not on Wynncraft, so there's no issues on any other servers. Artemis should do the same

**Comment by magicus** [comment]
We used to start all even handlers with a "if !onWorld return;", more or less. (There are exceptions for stuff happening before logon.) This has not been done consistently. (Thought I doubt my recent refactoring did anything to change this particular bug.)

We might even consider if we should move that logic to when we send out the event... That would make everything more robust. Care needs to be taken for events needed to confirm that we are online, though...

**Comment by kristofbolyai** [comment]
Fixing #23 would be a nice start

**Comment by KaspianDev** [comment]
Yep I agree it should only enable modifications to wynncraft (except of gamma?)
