### ISSUE TITLE
Crash on joining Wynncraft

### ISSUE THREAD

**Issue by ghost** [Wynntils/Wynntils#715]
**Version**
0.0.1-alpha.64

**Brief Description**
When I join Wynncraft, the game crashes with "Pose stack not empty"

**Steps to Reproduce**
1. Join `play.wynncraft.com`
2. Select character
3. Move camera around

**Crash Report**
https://paste.ee/p/BBT8L

**Installed Mods**
[Wynntils 0.0.1-alpha.64](https://github.com/Wynntils/Artemis/releases/tag/v0.0.1-alpha.64)
[Fabric API 0.66.0](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4073282)
Fabric Loader 0.14.10

**Comment by kristofbolyai** [comment]
Remove FAPI, it is not needed for Wynntils. I will check the issue out later.

**Comment by ghost** [comment]
Removing FAPI did not fix the crashing issues.

**Comment by kristofbolyai** [comment]
REALLY weird... This crash is always an interaction with some other mod...

**Comment by kristofbolyai** [comment]
Can you send the logs without fapi?

**Comment by ghost** [comment]
I have found out the crashing was caused by my MultiMC instance.

Deleting that instance and making a new one fixed the crashing.
