### ISSUE TITLE
KeyHolder's keybind gets reset after relaunch

### ISSUE THREAD

**Issue by KaspianDev** [Wynntils/Wynntils#73]
Like in title. Straight forward to reproduce
1. Change default hotkeys
2. Relaunch the game
3. Notice they reset

**Comment by KaspianDev** [comment]
(could apply to both but not confirmed)

**Comment by magicus** [comment]
That's a known issue. We don't save configurations yet.

**Comment by kristofbolyai** [comment]
> That's a known issue. We don't save configurations yet.

I mean, KeyMappings are saved by minecraft though? Also, it works on forge

**Comment by magicus** [comment]
Hm...

**Comment by kristofbolyai** [comment]
If I had to bet, this is something to do with a specific fabric api module not being used. (although last time it was only a problem in dev env)
