### ISSUE TITLE
/update isn't recognizing DEV environment

### ISSUE THREAD

**Issue by san7890** [Wynntils/Wynntils#756]
Reproduction is compiling a version of latest commit, and then trying to do `/wynntils update`. Then, get the following chat message.

![image](https://user-images.githubusercontent.com/34697715/204698190-a82f18ea-6001-42f9-95cf-fbf0971b9d3c.png)

It seems that the code here isn't working for some reason, since it allows me to proceed to the later "installation" parts:
https://github.com/Wynntils/Artemis/blob/3158eff0c515268aa57760d2a3e7cd695fa372fc/common/src/main/java/com/wynntils/commands/UpdateCommand.java#L24-L32

It doesn't seem to download anything though (maybe I'm looking in the wrong spot). I'm compiling for Fabric.

**Comment by kristofbolyai** [comment]
Do you actually run dev builds from run configurations or just compile builds with dev version? Latter is not a dev environment.

**Comment by san7890** [comment]
Yeah, the latter. Good to know, then.
