### ISSUE TITLE
[Bug] When making a waypoint in the map, tabbing between text boxes moves the visual cursor, but types in the previous box

### ISSUE THREAD

**Issue by jonathansharpe** [Wynntils/Wynntils#803]
If a user goes to create a waypoint in the map screen, type in the "Waypoint Name" box, then press `Tab`, the cursor moves to the "X Coordinate" box. However, if you start typing, the text will still appear in the "Waypoint Name" box, and not the "X Coordinate" box where it should. This applies when tabbing between any of the text boxes in the waypoint creation screen.

This could also apply to other menus in the mod as well, but this is the one where I've noticed it.

**Comment by kristofbolyai** [comment]
I fixed this a while back, forgot there was an issue made.
