### ISSUE TITLE
Replace the UncoloredSystemPatterns for crafted and tool durability redirectors

### ISSUE THREAD

**Issue by magicus** [Wynntils/Wynntils#820]
There are just two Redirectors left in ChatRedirectFeature which has regex matchers that do not include formatting codes, this is:

`Your items are damaged and have become less effective. Bring them to a Blacksmith to repair them.`

and 

`Your tool has 0 durability left! You will not receive any new resources until you repair it at a Blacksmith.`

We need to determine the proper chat message sent for these events, including formatting codes. Then we can replace the calls to `getUncoloredSystemPattern()` with proper `getSystemPattern()`.

**Comment by PhoenixOrigin** [comment]
So do I just need to get the full regex for these messages? I can do that.

**Comment by magicus** [comment]
@PhoenixOrigin, Yes exactly. Including the `§` formatting codes. It's likely to be something simple, like a single `§c` in the start.

**Comment by magicus** [comment]
@PhoenixOrigin Did you get anywhere with this? We will need to remove the distinction between `SYSTEM` and `NORMAL` chat messages in the 1.19 port (due to changes in Wynncraft), so this is becoming slightly more urgent.

**Comment by PhoenixOrigin** [comment]
I will get the reger today sorry been rlly busy
