### ISSUE TITLE
Every consumer of Wynntils Account Tokens should be able to run asynchronously 

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#829]
See https://github.com/Wynntils/Artemis/pull/826#discussion_r1048942877.

**Comment by magicus** [comment]
I think this is best solved by sending out an "We are now logged in"-event.

**Comment by kristofbolyai** [comment]
This same problem causes a weird interaction on `WynntilsAccountManager#login`. We have to get rid of `future#get`, because the second api call waits for that. That means that the mod thinks we always fail to set up account, when in reality, it finishes as soon as we stop waiting.
