### ISSUE TITLE
Modmenu button overlaps back to hub button

### ISSUE THREAD

**Issue by Hoi15A** [Wynntils/Wynntils#962]
If you use the adjacent setting for the Mod Menu button then it will overlap with the Back to hub button from artemis
![image](https://user-images.githubusercontent.com/10325316/210234059-8b78d0c3-42e8-4b23-8380-d01400a2510a.png)

**Comment by magicus** [comment]
Interacting with mod menu is a pain (I know from experience from other mods)...

**Comment by kristofbolyai** [comment]
This was fixed a long time ago.
