### ISSUE TITLE
[Overlay Display Problem] The Alignment of powderSpecialBarOverlay is shifted

### ISSUE THREAD

**Issue by Jimmy-sheep** [Wynntils/Wynntils#995]
The overlay of Powder Ability Bar is shifted and not align with health bar or mana bar(As the picture below), I have a little bit OCD, and this make me feel a bit uncomfortable.
Also, I hope other bars can also have option can change style to same as health bar.

Here is the part of code in my conf.json file.
 ```
  "customBarsOverlayFeature.healthBarOverlay.position": {
    "verticalOffset": 8.0,
    "horizontalOffset": -50.0,
    "verticalAlignment": "Middle",
    "horizontalAlignment": "Center",
    "anchorSection": "BottomMiddle"
  },
  "customBarsOverlayFeature.healthBarOverlay.size": {
    "width": 80.0,
    "height": 20.0
  },
  "customBarsOverlayFeature.healthBarOverlay.userEnabled": true,
  "customBarsOverlayFeature.healthBarOverlay.horizontalAlignmentOverride": "Center",
  "customBarsOverlayFeature.healthBarOverlay.verticalAlignmentOverride": "Middle",
```
```
  "powderSpecialBarOverlayFeature.powderSpecialBarOverlay.position": {
    "verticalOffset": 8.0,
    "horizontalOffset": 150.0,
    "verticalAlignment": "Middle",
    "horizontalAlignment": "Center",
    "anchorSection": "BottomMiddle"
  },
  "powderSpecialBarOverlayFeature.powderSpecialBarOverlay.size": {
    "width": 80.0,
    "height": 20.0
  },
  "powderSpecialBarOverlayFeature.powderSpecialBarOverlay.userEnabled": true,
  "powderSpecialBarOverlayFeature.powderSpecialBarOverlay.horizontalAlignmentOverride": "Center",
  "powderSpecialBarOverlayFeature.powderSpecialBarOverlay.verticalAlignmentOverride": "Middle",
```

![image](https://user-images.githubusercontent.com/65125836/211200162-ca157f75-9430-4a50-9c22-c14360f86fc6.png)
![image](https://user-images.githubusercontent.com/65125836/211200170-8411c641-6f7a-4e36-8cd1-86106186b6c5.png)

**Comment by magicus** [comment]
I think you need to make it aligned to the top. Select the powder special bar, and press shift+up (or possibly just up). Do it several times if it does not get right the first time.

**Comment by Jimmy-sheep** [comment]
> I think you need to make it aligned to the top. Select the powder special bar, and press shift+up (or possibly just up). Do it several times if it does not get right the first time.

But in health bar(and mana bar), the `verticalAlignmentOverride` is also in `Middle`, and it display well.

**Comment by Jimmy-sheep** [comment]
Whatever, I change all into `Top`, and its well now, thanks.

![image](https://user-images.githubusercontent.com/65125836/211206449-7cf710e2-7e3e-457e-8122-d3bb514ae7af.png)

**Comment by magicus** [comment]
We should probably look into the default values, so it looks good by default.
